/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AgeRatingTitle = {
    Three: 'Three',
    Seven: 'Seven',
    Twelve: 'Twelve',
    Sixteen: 'Sixteen',
    Eighteen: 'Eighteen',
    Rp: 'RP',
    Ec: 'EC',
    E: 'E',
    E10: 'E10',
    T: 'T',
    M: 'M',
    Ao: 'AO',
    CeroA: 'CERO_A',
    CeroB: 'CERO_B',
    CeroC: 'CERO_C',
    CeroD: 'CERO_D',
    CeroZ: 'CERO_Z',
    Usk0: 'USK_0',
    Usk6: 'USK_6',
    Usk12: 'USK_12',
    Usk16: 'USK_16',
    Usk18: 'USK_18',
    GracAll: 'GRAC_All',
    GracTwelve: 'GRAC_Twelve',
    GracFifteen: 'GRAC_Fifteen',
    GracEighteen: 'GRAC_Eighteen',
    GracTesting: 'GRAC_Testing',
    ClassIndL: 'CLASS_IND_L',
    ClassIndTen: 'CLASS_IND_Ten',
    ClassIndTwelve: 'CLASS_IND_Twelve',
    ClassIndFourteen: 'CLASS_IND_Fourteen',
    ClassIndSixteen: 'CLASS_IND_Sixteen',
    ClassIndEighteen: 'CLASS_IND_Eighteen',
    AcbG: 'ACB_G',
    AcbPg: 'ACB_PG',
    AcbM: 'ACB_M',
    AcbMa15: 'ACB_MA15',
    AcbR18: 'ACB_R18',
    AcbRc: 'ACB_RC'
} as const;
export type AgeRatingTitle = typeof AgeRatingTitle[keyof typeof AgeRatingTitle];


export function instanceOfAgeRatingTitle(value: any): boolean {
    for (const key in AgeRatingTitle) {
        if (Object.prototype.hasOwnProperty.call(AgeRatingTitle, key)) {
            if (AgeRatingTitle[key as keyof typeof AgeRatingTitle] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AgeRatingTitleFromJSON(json: any): AgeRatingTitle {
    return AgeRatingTitleFromJSONTyped(json, false);
}

export function AgeRatingTitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRatingTitle {
    return json as AgeRatingTitle;
}

export function AgeRatingTitleToJSON(value?: AgeRatingTitle | null): any {
    return value as any;
}

export function AgeRatingTitleToJSONTyped(value: any, ignoreDiscriminator: boolean): AgeRatingTitle {
    return value as AgeRatingTitle;
}

