/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgeRatingOrganization
 */
export interface AgeRatingOrganization {
    /**
     * 
     * @type {string}
     * @memberof AgeRatingOrganization
     */
    checksum?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgeRatingOrganization
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgeRatingOrganization
     */
    id?: number | null;
}

/**
 * Check if a given object implements the AgeRatingOrganization interface.
 */
export function instanceOfAgeRatingOrganization(value: object): value is AgeRatingOrganization {
    return true;
}

export function AgeRatingOrganizationFromJSON(json: any): AgeRatingOrganization {
    return AgeRatingOrganizationFromJSONTyped(json, false);
}

export function AgeRatingOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRatingOrganization {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AgeRatingOrganizationToJSON(json: any): AgeRatingOrganization {
    return AgeRatingOrganizationToJSONTyped(json, false);
}

export function AgeRatingOrganizationToJSONTyped(value?: AgeRatingOrganization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'name': value['name'],
        'id': value['id'],
    };
}

