/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgeRatingContentDescription } from './AgeRatingContentDescription';
import {
    AgeRatingContentDescriptionFromJSON,
    AgeRatingContentDescriptionFromJSONTyped,
    AgeRatingContentDescriptionToJSON,
    AgeRatingContentDescriptionToJSONTyped,
} from './AgeRatingContentDescription';

/**
 * 
 * @export
 * @interface AgeRatingContentDescriptionIdentitiesOrValues
 */
export interface AgeRatingContentDescriptionIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof AgeRatingContentDescriptionIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<AgeRatingContentDescription>}
     * @memberof AgeRatingContentDescriptionIdentitiesOrValues
     */
    readonly values?: Array<AgeRatingContentDescription> | null;
}

/**
 * Check if a given object implements the AgeRatingContentDescriptionIdentitiesOrValues interface.
 */
export function instanceOfAgeRatingContentDescriptionIdentitiesOrValues(value: object): value is AgeRatingContentDescriptionIdentitiesOrValues {
    return true;
}

export function AgeRatingContentDescriptionIdentitiesOrValuesFromJSON(json: any): AgeRatingContentDescriptionIdentitiesOrValues {
    return AgeRatingContentDescriptionIdentitiesOrValuesFromJSONTyped(json, false);
}

export function AgeRatingContentDescriptionIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRatingContentDescriptionIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(AgeRatingContentDescriptionFromJSON)),
    };
}

export function AgeRatingContentDescriptionIdentitiesOrValuesToJSON(json: any): AgeRatingContentDescriptionIdentitiesOrValues {
    return AgeRatingContentDescriptionIdentitiesOrValuesToJSONTyped(json, false);
}

export function AgeRatingContentDescriptionIdentitiesOrValuesToJSONTyped(value?: Omit<AgeRatingContentDescriptionIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

