/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgeRatingCategory } from './AgeRatingCategory';
import {
    AgeRatingCategoryFromJSON,
    AgeRatingCategoryFromJSONTyped,
    AgeRatingCategoryToJSON,
    AgeRatingCategoryToJSONTyped,
} from './AgeRatingCategory';

/**
 * 
 * @export
 * @interface AgeRatingCategoryIdentityOrValue
 */
export interface AgeRatingCategoryIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof AgeRatingCategoryIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {AgeRatingCategory}
     * @memberof AgeRatingCategoryIdentityOrValue
     */
    readonly value?: AgeRatingCategory | null;
}

/**
 * Check if a given object implements the AgeRatingCategoryIdentityOrValue interface.
 */
export function instanceOfAgeRatingCategoryIdentityOrValue(value: object): value is AgeRatingCategoryIdentityOrValue {
    return true;
}

export function AgeRatingCategoryIdentityOrValueFromJSON(json: any): AgeRatingCategoryIdentityOrValue {
    return AgeRatingCategoryIdentityOrValueFromJSONTyped(json, false);
}

export function AgeRatingCategoryIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRatingCategoryIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : AgeRatingCategoryFromJSON(json['value']),
    };
}

export function AgeRatingCategoryIdentityOrValueToJSON(json: any): AgeRatingCategoryIdentityOrValue {
    return AgeRatingCategoryIdentityOrValueToJSONTyped(json, false);
}

export function AgeRatingCategoryIdentityOrValueToJSONTyped(value?: Omit<AgeRatingCategoryIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

