/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgeRatingOrganizationIdentityOrValue } from './AgeRatingOrganizationIdentityOrValue';
import {
    AgeRatingOrganizationIdentityOrValueFromJSON,
    AgeRatingOrganizationIdentityOrValueFromJSONTyped,
    AgeRatingOrganizationIdentityOrValueToJSON,
    AgeRatingOrganizationIdentityOrValueToJSONTyped,
} from './AgeRatingOrganizationIdentityOrValue';

/**
 * 
 * @export
 * @interface AgeRatingContentDescriptionV2
 */
export interface AgeRatingContentDescriptionV2 {
    /**
     * 
     * @type {string}
     * @memberof AgeRatingContentDescriptionV2
     */
    checksum?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AgeRatingContentDescriptionV2
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {AgeRatingOrganizationIdentityOrValue}
     * @memberof AgeRatingContentDescriptionV2
     */
    organization?: AgeRatingOrganizationIdentityOrValue | null;
    /**
     * 
     * @type {string}
     * @memberof AgeRatingContentDescriptionV2
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgeRatingContentDescriptionV2
     */
    id?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AgeRatingContentDescriptionV2
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the AgeRatingContentDescriptionV2 interface.
 */
export function instanceOfAgeRatingContentDescriptionV2(value: object): value is AgeRatingContentDescriptionV2 {
    return true;
}

export function AgeRatingContentDescriptionV2FromJSON(json: any): AgeRatingContentDescriptionV2 {
    return AgeRatingContentDescriptionV2FromJSONTyped(json, false);
}

export function AgeRatingContentDescriptionV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRatingContentDescriptionV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'organization': json['organization'] == null ? undefined : AgeRatingOrganizationIdentityOrValueFromJSON(json['organization']),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function AgeRatingContentDescriptionV2ToJSON(json: any): AgeRatingContentDescriptionV2 {
    return AgeRatingContentDescriptionV2ToJSONTyped(json, false);
}

export function AgeRatingContentDescriptionV2ToJSONTyped(value?: AgeRatingContentDescriptionV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'organization': AgeRatingOrganizationIdentityOrValueToJSON(value['organization']),
        'description': value['description'],
        'id': value['id'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

