/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ChangeDateCategory = {
    Yyyymmmmdd: 'YYYYMMMMDD',
    Yyyymmmm: 'YYYYMMMM',
    Yyyy: 'YYYY',
    Yyyyq1: 'YYYYQ1',
    Yyyyq2: 'YYYYQ2',
    Yyyyq3: 'YYYYQ3',
    Yyyyq4: 'YYYYQ4',
    Tbd: 'TBD'
} as const;
export type ChangeDateCategory = typeof ChangeDateCategory[keyof typeof ChangeDateCategory];


export function instanceOfChangeDateCategory(value: any): boolean {
    for (const key in ChangeDateCategory) {
        if (Object.prototype.hasOwnProperty.call(ChangeDateCategory, key)) {
            if (ChangeDateCategory[key as keyof typeof ChangeDateCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChangeDateCategoryFromJSON(json: any): ChangeDateCategory {
    return ChangeDateCategoryFromJSONTyped(json, false);
}

export function ChangeDateCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeDateCategory {
    return json as ChangeDateCategory;
}

export function ChangeDateCategoryToJSON(value?: ChangeDateCategory | null): any {
    return value as any;
}

export function ChangeDateCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): ChangeDateCategory {
    return value as ChangeDateCategory;
}

