/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * 
 * @export
 * @interface CollectionIdentitiesOrValues
 */
export interface CollectionIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof CollectionIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<Collection>}
     * @memberof CollectionIdentitiesOrValues
     */
    readonly values?: Array<Collection> | null;
}

/**
 * Check if a given object implements the CollectionIdentitiesOrValues interface.
 */
export function instanceOfCollectionIdentitiesOrValues(value: object): value is CollectionIdentitiesOrValues {
    return true;
}

export function CollectionIdentitiesOrValuesFromJSON(json: any): CollectionIdentitiesOrValues {
    return CollectionIdentitiesOrValuesFromJSONTyped(json, false);
}

export function CollectionIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(CollectionFromJSON)),
    };
}

export function CollectionIdentitiesOrValuesToJSON(json: any): CollectionIdentitiesOrValues {
    return CollectionIdentitiesOrValuesToJSONTyped(json, false);
}

export function CollectionIdentitiesOrValuesToJSONTyped(value?: Omit<CollectionIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

