/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionType } from './CollectionType';
import {
    CollectionTypeFromJSON,
    CollectionTypeFromJSONTyped,
    CollectionTypeToJSON,
    CollectionTypeToJSONTyped,
} from './CollectionType';

/**
 * 
 * @export
 * @interface CollectionTypeIdentityOrValue
 */
export interface CollectionTypeIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof CollectionTypeIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {CollectionType}
     * @memberof CollectionTypeIdentityOrValue
     */
    readonly value?: CollectionType | null;
}

/**
 * Check if a given object implements the CollectionTypeIdentityOrValue interface.
 */
export function instanceOfCollectionTypeIdentityOrValue(value: object): value is CollectionTypeIdentityOrValue {
    return true;
}

export function CollectionTypeIdentityOrValueFromJSON(json: any): CollectionTypeIdentityOrValue {
    return CollectionTypeIdentityOrValueFromJSONTyped(json, false);
}

export function CollectionTypeIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionTypeIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : CollectionTypeFromJSON(json['value']),
    };
}

export function CollectionTypeIdentityOrValueToJSON(json: any): CollectionTypeIdentityOrValue {
    return CollectionTypeIdentityOrValueToJSONTyped(json, false);
}

export function CollectionTypeIdentityOrValueToJSONTyped(value?: Omit<CollectionTypeIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

