/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * 
 * @export
 * @interface CollectionIdentityOrValue
 */
export interface CollectionIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof CollectionIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {Collection}
     * @memberof CollectionIdentityOrValue
     */
    readonly value?: Collection | null;
}

/**
 * Check if a given object implements the CollectionIdentityOrValue interface.
 */
export function instanceOfCollectionIdentityOrValue(value: object): value is CollectionIdentityOrValue {
    return true;
}

export function CollectionIdentityOrValueFromJSON(json: any): CollectionIdentityOrValue {
    return CollectionIdentityOrValueFromJSONTyped(json, false);
}

export function CollectionIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : CollectionFromJSON(json['value']),
    };
}

export function CollectionIdentityOrValueToJSON(json: any): CollectionIdentityOrValue {
    return CollectionIdentityOrValueToJSONTyped(json, false);
}

export function CollectionIdentityOrValueToJSONTyped(value?: Omit<CollectionIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

