/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
    CompanyToJSONTyped,
} from './Company';

/**
 * 
 * @export
 * @interface CompanyIdentitiesOrValues
 */
export interface CompanyIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof CompanyIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<Company>}
     * @memberof CompanyIdentitiesOrValues
     */
    readonly values?: Array<Company> | null;
}

/**
 * Check if a given object implements the CompanyIdentitiesOrValues interface.
 */
export function instanceOfCompanyIdentitiesOrValues(value: object): value is CompanyIdentitiesOrValues {
    return true;
}

export function CompanyIdentitiesOrValuesFromJSON(json: any): CompanyIdentitiesOrValues {
    return CompanyIdentitiesOrValuesFromJSONTyped(json, false);
}

export function CompanyIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(CompanyFromJSON)),
    };
}

export function CompanyIdentitiesOrValuesToJSON(json: any): CompanyIdentitiesOrValues {
    return CompanyIdentitiesOrValuesToJSONTyped(json, false);
}

export function CompanyIdentitiesOrValuesToJSONTyped(value?: Omit<CompanyIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

