/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
    CompanyToJSONTyped,
} from './Company';

/**
 * 
 * @export
 * @interface CompanyIdentityOrValue
 */
export interface CompanyIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof CompanyIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {Company}
     * @memberof CompanyIdentityOrValue
     */
    readonly value?: Company | null;
}

/**
 * Check if a given object implements the CompanyIdentityOrValue interface.
 */
export function instanceOfCompanyIdentityOrValue(value: object): value is CompanyIdentityOrValue {
    return true;
}

export function CompanyIdentityOrValueFromJSON(json: any): CompanyIdentityOrValue {
    return CompanyIdentityOrValueFromJSONTyped(json, false);
}

export function CompanyIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : CompanyFromJSON(json['value']),
    };
}

export function CompanyIdentityOrValueToJSON(json: any): CompanyIdentityOrValue {
    return CompanyIdentityOrValueToJSONTyped(json, false);
}

export function CompanyIdentityOrValueToJSONTyped(value?: Omit<CompanyIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

