/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameLocalizationIdentityOrValue } from './GameLocalizationIdentityOrValue';
import {
    GameLocalizationIdentityOrValueFromJSON,
    GameLocalizationIdentityOrValueFromJSONTyped,
    GameLocalizationIdentityOrValueToJSON,
    GameLocalizationIdentityOrValueToJSONTyped,
} from './GameLocalizationIdentityOrValue';
import type { GameIdentityOrValue } from './GameIdentityOrValue';
import {
    GameIdentityOrValueFromJSON,
    GameIdentityOrValueFromJSONTyped,
    GameIdentityOrValueToJSON,
    GameIdentityOrValueToJSONTyped,
} from './GameIdentityOrValue';

/**
 * 
 * @export
 * @interface Cover
 */
export interface Cover {
    /**
     * 
     * @type {boolean}
     * @memberof Cover
     */
    alphaChannel?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof Cover
     */
    animated?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    checksum?: string | null;
    /**
     * 
     * @type {GameIdentityOrValue}
     * @memberof Cover
     */
    game?: GameIdentityOrValue | null;
    /**
     * 
     * @type {GameLocalizationIdentityOrValue}
     * @memberof Cover
     */
    gameLocalization?: GameLocalizationIdentityOrValue | null;
    /**
     * 
     * @type {number}
     * @memberof Cover
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Cover
     */
    height?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    imageId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    url?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Cover
     */
    width?: number | null;
}

/**
 * Check if a given object implements the Cover interface.
 */
export function instanceOfCover(value: object): value is Cover {
    return true;
}

export function CoverFromJSON(json: any): Cover {
    return CoverFromJSONTyped(json, false);
}

export function CoverFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cover {
    if (json == null) {
        return json;
    }
    return {
        
        'alphaChannel': json['alphaChannel'] == null ? undefined : json['alphaChannel'],
        'animated': json['animated'] == null ? undefined : json['animated'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'game': json['game'] == null ? undefined : GameIdentityOrValueFromJSON(json['game']),
        'gameLocalization': json['gameLocalization'] == null ? undefined : GameLocalizationIdentityOrValueFromJSON(json['gameLocalization']),
        'id': json['id'] == null ? undefined : json['id'],
        'height': json['height'] == null ? undefined : json['height'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'url': json['url'] == null ? undefined : json['url'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function CoverToJSON(json: any): Cover {
    return CoverToJSONTyped(json, false);
}

export function CoverToJSONTyped(value?: Cover | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alphaChannel': value['alphaChannel'],
        'animated': value['animated'],
        'checksum': value['checksum'],
        'game': GameIdentityOrValueToJSON(value['game']),
        'gameLocalization': GameLocalizationIdentityOrValueToJSON(value['gameLocalization']),
        'id': value['id'],
        'height': value['height'],
        'imageId': value['imageId'],
        'url': value['url'],
        'width': value['width'],
    };
}

