/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateFormat } from './DateFormat';
import {
    DateFormatFromJSON,
    DateFormatFromJSONTyped,
    DateFormatToJSON,
    DateFormatToJSONTyped,
} from './DateFormat';

/**
 * 
 * @export
 * @interface DateFormatIdentityOrValue
 */
export interface DateFormatIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof DateFormatIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {DateFormat}
     * @memberof DateFormatIdentityOrValue
     */
    readonly value?: DateFormat | null;
}

/**
 * Check if a given object implements the DateFormatIdentityOrValue interface.
 */
export function instanceOfDateFormatIdentityOrValue(value: object): value is DateFormatIdentityOrValue {
    return true;
}

export function DateFormatIdentityOrValueFromJSON(json: any): DateFormatIdentityOrValue {
    return DateFormatIdentityOrValueFromJSONTyped(json, false);
}

export function DateFormatIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateFormatIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : DateFormatFromJSON(json['value']),
    };
}

export function DateFormatIdentityOrValueToJSON(json: any): DateFormatIdentityOrValue {
    return DateFormatIdentityOrValueToJSONTyped(json, false);
}

export function DateFormatIdentityOrValueToJSONTyped(value?: Omit<DateFormatIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

