/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetectedServer
 */
export interface DetectedServer {
    /**
     * 
     * @type {string}
     * @memberof DetectedServer
     */
    gameSlug?: string;
    /**
     * 
     * @type {number}
     * @memberof DetectedServer
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof DetectedServer
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof DetectedServer
     */
    processName?: string;
    /**
     * 
     * @type {number}
     * @memberof DetectedServer
     */
    pid?: number;
    /**
     * 
     * @type {Date}
     * @memberof DetectedServer
     */
    startTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DetectedServer
     */
    uptime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetectedServer
     */
    memoryMb?: number | null;
}

/**
 * Check if a given object implements the DetectedServer interface.
 */
export function instanceOfDetectedServer(value: object): value is DetectedServer {
    return true;
}

export function DetectedServerFromJSON(json: any): DetectedServer {
    return DetectedServerFromJSONTyped(json, false);
}

export function DetectedServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectedServer {
    if (json == null) {
        return json;
    }
    return {
        
        'gameSlug': json['gameSlug'] == null ? undefined : json['gameSlug'],
        'port': json['port'] == null ? undefined : json['port'],
        'type': json['type'] == null ? undefined : json['type'],
        'processName': json['processName'] == null ? undefined : json['processName'],
        'pid': json['pid'] == null ? undefined : json['pid'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'uptime': json['uptime'] == null ? undefined : json['uptime'],
        'memoryMb': json['memoryMb'] == null ? undefined : json['memoryMb'],
    };
}

export function DetectedServerToJSON(json: any): DetectedServer {
    return DetectedServerToJSONTyped(json, false);
}

export function DetectedServerToJSONTyped(value?: DetectedServer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gameSlug': value['gameSlug'],
        'port': value['port'],
        'type': value['type'],
        'processName': value['processName'],
        'pid': value['pid'],
        'startTime': value['startTime'] == null ? undefined : ((value['startTime'] as any).toISOString()),
        'uptime': value['uptime'],
        'memoryMb': value['memoryMb'],
    };
}

