/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExternalGameMedia = {
    Digital: 'Digital',
    Physical: 'Physical'
} as const;
export type ExternalGameMedia = typeof ExternalGameMedia[keyof typeof ExternalGameMedia];


export function instanceOfExternalGameMedia(value: any): boolean {
    for (const key in ExternalGameMedia) {
        if (Object.prototype.hasOwnProperty.call(ExternalGameMedia, key)) {
            if (ExternalGameMedia[key as keyof typeof ExternalGameMedia] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExternalGameMediaFromJSON(json: any): ExternalGameMedia {
    return ExternalGameMediaFromJSONTyped(json, false);
}

export function ExternalGameMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalGameMedia {
    return json as ExternalGameMedia;
}

export function ExternalGameMediaToJSON(value?: ExternalGameMedia | null): any {
    return value as any;
}

export function ExternalGameMediaToJSONTyped(value: any, ignoreDiscriminator: boolean): ExternalGameMedia {
    return value as ExternalGameMedia;
}

