/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameReleaseFormatIdentityOrValue } from './GameReleaseFormatIdentityOrValue';
import {
    GameReleaseFormatIdentityOrValueFromJSON,
    GameReleaseFormatIdentityOrValueFromJSONTyped,
    GameReleaseFormatIdentityOrValueToJSON,
    GameReleaseFormatIdentityOrValueToJSONTyped,
} from './GameReleaseFormatIdentityOrValue';
import type { PlatformIdentityOrValue } from './PlatformIdentityOrValue';
import {
    PlatformIdentityOrValueFromJSON,
    PlatformIdentityOrValueFromJSONTyped,
    PlatformIdentityOrValueToJSON,
    PlatformIdentityOrValueToJSONTyped,
} from './PlatformIdentityOrValue';
import type { ExternalGameSourceIdentityOrValue } from './ExternalGameSourceIdentityOrValue';
import {
    ExternalGameSourceIdentityOrValueFromJSON,
    ExternalGameSourceIdentityOrValueFromJSONTyped,
    ExternalGameSourceIdentityOrValueToJSON,
    ExternalGameSourceIdentityOrValueToJSONTyped,
} from './ExternalGameSourceIdentityOrValue';
import type { GameIdentityOrValue } from './GameIdentityOrValue';
import {
    GameIdentityOrValueFromJSON,
    GameIdentityOrValueFromJSONTyped,
    GameIdentityOrValueToJSON,
    GameIdentityOrValueToJSONTyped,
} from './GameIdentityOrValue';

/**
 * 
 * @export
 * @interface ExternalGame
 */
export interface ExternalGame {
    /**
     * 
     * @type {string}
     * @memberof ExternalGame
     */
    checksum?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExternalGame
     */
    countries?: Array<number> | null;
    /**
     * 
     * @type {Date}
     * @memberof ExternalGame
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {ExternalGameSourceIdentityOrValue}
     * @memberof ExternalGame
     */
    externalGameSource?: ExternalGameSourceIdentityOrValue | null;
    /**
     * 
     * @type {GameIdentityOrValue}
     * @memberof ExternalGame
     */
    game?: GameIdentityOrValue | null;
    /**
     * 
     * @type {GameReleaseFormatIdentityOrValue}
     * @memberof ExternalGame
     */
    gameReleaseFormat?: GameReleaseFormatIdentityOrValue | null;
    /**
     * 
     * @type {number}
     * @memberof ExternalGame
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalGame
     */
    name?: string | null;
    /**
     * 
     * @type {PlatformIdentityOrValue}
     * @memberof ExternalGame
     */
    platform?: PlatformIdentityOrValue | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalGame
     */
    uid?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ExternalGame
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalGame
     */
    url?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExternalGame
     */
    year?: number | null;
}

/**
 * Check if a given object implements the ExternalGame interface.
 */
export function instanceOfExternalGame(value: object): value is ExternalGame {
    return true;
}

export function ExternalGameFromJSON(json: any): ExternalGame {
    return ExternalGameFromJSONTyped(json, false);
}

export function ExternalGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalGame {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'countries': json['countries'] == null ? undefined : json['countries'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'externalGameSource': json['externalGameSource'] == null ? undefined : ExternalGameSourceIdentityOrValueFromJSON(json['externalGameSource']),
        'game': json['game'] == null ? undefined : GameIdentityOrValueFromJSON(json['game']),
        'gameReleaseFormat': json['gameReleaseFormat'] == null ? undefined : GameReleaseFormatIdentityOrValueFromJSON(json['gameReleaseFormat']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'platform': json['platform'] == null ? undefined : PlatformIdentityOrValueFromJSON(json['platform']),
        'uid': json['uid'] == null ? undefined : json['uid'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'url': json['url'] == null ? undefined : json['url'],
        'year': json['year'] == null ? undefined : json['year'],
    };
}

export function ExternalGameToJSON(json: any): ExternalGame {
    return ExternalGameToJSONTyped(json, false);
}

export function ExternalGameToJSONTyped(value?: ExternalGame | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'countries': value['countries'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'externalGameSource': ExternalGameSourceIdentityOrValueToJSON(value['externalGameSource']),
        'game': GameIdentityOrValueToJSON(value['game']),
        'gameReleaseFormat': GameReleaseFormatIdentityOrValueToJSON(value['gameReleaseFormat']),
        'id': value['id'],
        'name': value['name'],
        'platform': PlatformIdentityOrValueToJSON(value['platform']),
        'uid': value['uid'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'url': value['url'],
        'year': value['year'],
    };
}

