/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Game } from './Game';
import {
    GameFromJSON,
    GameFromJSONTyped,
    GameToJSON,
    GameToJSONTyped,
} from './Game';

/**
 * 
 * @export
 * @interface GameIdentityOrValue
 */
export interface GameIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof GameIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {Game}
     * @memberof GameIdentityOrValue
     */
    readonly value?: Game | null;
}

/**
 * Check if a given object implements the GameIdentityOrValue interface.
 */
export function instanceOfGameIdentityOrValue(value: object): value is GameIdentityOrValue {
    return true;
}

export function GameIdentityOrValueFromJSON(json: any): GameIdentityOrValue {
    return GameIdentityOrValueFromJSONTyped(json, false);
}

export function GameIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : GameFromJSON(json['value']),
    };
}

export function GameIdentityOrValueToJSON(json: any): GameIdentityOrValue {
    return GameIdentityOrValueToJSONTyped(json, false);
}

export function GameIdentityOrValueToJSONTyped(value?: Omit<GameIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

