/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameLocalization } from './GameLocalization';
import {
    GameLocalizationFromJSON,
    GameLocalizationFromJSONTyped,
    GameLocalizationToJSON,
    GameLocalizationToJSONTyped,
} from './GameLocalization';

/**
 * 
 * @export
 * @interface GameLocalizationIdentitiesOrValues
 */
export interface GameLocalizationIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof GameLocalizationIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<GameLocalization>}
     * @memberof GameLocalizationIdentitiesOrValues
     */
    readonly values?: Array<GameLocalization> | null;
}

/**
 * Check if a given object implements the GameLocalizationIdentitiesOrValues interface.
 */
export function instanceOfGameLocalizationIdentitiesOrValues(value: object): value is GameLocalizationIdentitiesOrValues {
    return true;
}

export function GameLocalizationIdentitiesOrValuesFromJSON(json: any): GameLocalizationIdentitiesOrValues {
    return GameLocalizationIdentitiesOrValuesFromJSONTyped(json, false);
}

export function GameLocalizationIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameLocalizationIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(GameLocalizationFromJSON)),
    };
}

export function GameLocalizationIdentitiesOrValuesToJSON(json: any): GameLocalizationIdentitiesOrValues {
    return GameLocalizationIdentitiesOrValuesToJSONTyped(json, false);
}

export function GameLocalizationIdentitiesOrValuesToJSONTyped(value?: Omit<GameLocalizationIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

