/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameStatus } from './GameStatus';
import {
    GameStatusFromJSON,
    GameStatusFromJSONTyped,
    GameStatusToJSON,
    GameStatusToJSONTyped,
} from './GameStatus';

/**
 * 
 * @export
 * @interface GameStatusIdentityOrValue
 */
export interface GameStatusIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof GameStatusIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {GameStatus}
     * @memberof GameStatusIdentityOrValue
     */
    readonly value?: GameStatus | null;
}

/**
 * Check if a given object implements the GameStatusIdentityOrValue interface.
 */
export function instanceOfGameStatusIdentityOrValue(value: object): value is GameStatusIdentityOrValue {
    return true;
}

export function GameStatusIdentityOrValueFromJSON(json: any): GameStatusIdentityOrValue {
    return GameStatusIdentityOrValueFromJSONTyped(json, false);
}

export function GameStatusIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatusIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : GameStatusFromJSON(json['value']),
    };
}

export function GameStatusIdentityOrValueToJSON(json: any): GameStatusIdentityOrValue {
    return GameStatusIdentityOrValueToJSONTyped(json, false);
}

export function GameStatusIdentityOrValueToJSONTyped(value?: Omit<GameStatusIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

