/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameType
 */
export interface GameType {
    /**
     * 
     * @type {string}
     * @memberof GameType
     */
    checksum?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GameType
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GameType
     */
    type?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GameType
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof GameType
     */
    id?: number | null;
}

/**
 * Check if a given object implements the GameType interface.
 */
export function instanceOfGameType(value: object): value is GameType {
    return true;
}

export function GameTypeFromJSON(json: any): GameType {
    return GameTypeFromJSONTyped(json, false);
}

export function GameTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameType {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'type': json['type'] == null ? undefined : json['type'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function GameTypeToJSON(json: any): GameType {
    return GameTypeToJSONTyped(json, false);
}

export function GameTypeToJSONTyped(value?: GameType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'type': value['type'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'id': value['id'],
    };
}

