/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Game } from './Game';
import {
    GameFromJSON,
    GameFromJSONTyped,
    GameToJSON,
    GameToJSONTyped,
} from './Game';

/**
 * 
 * @export
 * @interface GameIdentitiesOrValues
 */
export interface GameIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof GameIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<Game>}
     * @memberof GameIdentitiesOrValues
     */
    readonly values?: Array<Game> | null;
}

/**
 * Check if a given object implements the GameIdentitiesOrValues interface.
 */
export function instanceOfGameIdentitiesOrValues(value: object): value is GameIdentitiesOrValues {
    return true;
}

export function GameIdentitiesOrValuesFromJSON(json: any): GameIdentitiesOrValues {
    return GameIdentitiesOrValuesFromJSONTyped(json, false);
}

export function GameIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(GameFromJSON)),
    };
}

export function GameIdentitiesOrValuesToJSON(json: any): GameIdentitiesOrValues {
    return GameIdentitiesOrValuesToJSONTyped(json, false);
}

export function GameIdentitiesOrValuesToJSONTyped(value?: Omit<GameIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

