/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameStatus
 */
export interface GameStatus {
    /**
     * 
     * @type {string}
     * @memberof GameStatus
     */
    checksum?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GameStatus
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GameStatus
     */
    status?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GameStatus
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof GameStatus
     */
    id?: number | null;
}

/**
 * Check if a given object implements the GameStatus interface.
 */
export function instanceOfGameStatus(value: object): value is GameStatus {
    return true;
}

export function GameStatusFromJSON(json: any): GameStatus {
    return GameStatusFromJSONTyped(json, false);
}

export function GameStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function GameStatusToJSON(json: any): GameStatus {
    return GameStatusToJSONTyped(json, false);
}

export function GameStatusToJSONTyped(value?: GameStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'status': value['status'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'id': value['id'],
    };
}

