/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyIdentitiesOrValues } from './CompanyIdentitiesOrValues';
import {
    CompanyIdentitiesOrValuesFromJSON,
    CompanyIdentitiesOrValuesFromJSONTyped,
    CompanyIdentitiesOrValuesToJSON,
    CompanyIdentitiesOrValuesToJSONTyped,
} from './CompanyIdentitiesOrValues';
import type { GameEngineLogoIdentityOrValue } from './GameEngineLogoIdentityOrValue';
import {
    GameEngineLogoIdentityOrValueFromJSON,
    GameEngineLogoIdentityOrValueFromJSONTyped,
    GameEngineLogoIdentityOrValueToJSON,
    GameEngineLogoIdentityOrValueToJSONTyped,
} from './GameEngineLogoIdentityOrValue';
import type { PlatformIdentitiesOrValues } from './PlatformIdentitiesOrValues';
import {
    PlatformIdentitiesOrValuesFromJSON,
    PlatformIdentitiesOrValuesFromJSONTyped,
    PlatformIdentitiesOrValuesToJSON,
    PlatformIdentitiesOrValuesToJSONTyped,
} from './PlatformIdentitiesOrValues';

/**
 * 
 * @export
 * @interface GameEngine
 */
export interface GameEngine {
    /**
     * 
     * @type {string}
     * @memberof GameEngine
     */
    checksum?: string | null;
    /**
     * 
     * @type {CompanyIdentitiesOrValues}
     * @memberof GameEngine
     */
    companies?: CompanyIdentitiesOrValues | null;
    /**
     * 
     * @type {Date}
     * @memberof GameEngine
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GameEngine
     */
    description?: string | null;
    /**
     * 
     * @type {GameEngineLogoIdentityOrValue}
     * @memberof GameEngine
     */
    logo?: GameEngineLogoIdentityOrValue | null;
    /**
     * 
     * @type {number}
     * @memberof GameEngine
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GameEngine
     */
    name?: string | null;
    /**
     * 
     * @type {PlatformIdentitiesOrValues}
     * @memberof GameEngine
     */
    platforms?: PlatformIdentitiesOrValues | null;
    /**
     * 
     * @type {string}
     * @memberof GameEngine
     */
    slug?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GameEngine
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GameEngine
     */
    url?: string | null;
}

/**
 * Check if a given object implements the GameEngine interface.
 */
export function instanceOfGameEngine(value: object): value is GameEngine {
    return true;
}

export function GameEngineFromJSON(json: any): GameEngine {
    return GameEngineFromJSONTyped(json, false);
}

export function GameEngineFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameEngine {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'companies': json['companies'] == null ? undefined : CompanyIdentitiesOrValuesFromJSON(json['companies']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'description': json['description'] == null ? undefined : json['description'],
        'logo': json['logo'] == null ? undefined : GameEngineLogoIdentityOrValueFromJSON(json['logo']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'platforms': json['platforms'] == null ? undefined : PlatformIdentitiesOrValuesFromJSON(json['platforms']),
        'slug': json['slug'] == null ? undefined : json['slug'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GameEngineToJSON(json: any): GameEngine {
    return GameEngineToJSONTyped(json, false);
}

export function GameEngineToJSONTyped(value?: GameEngine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'companies': CompanyIdentitiesOrValuesToJSON(value['companies']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'description': value['description'],
        'logo': GameEngineLogoIdentityOrValueToJSON(value['logo']),
        'id': value['id'],
        'name': value['name'],
        'platforms': PlatformIdentitiesOrValuesToJSON(value['platforms']),
        'slug': value['slug'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'url': value['url'],
    };
}

