/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Genre } from './Genre';
import {
    GenreFromJSON,
    GenreFromJSONTyped,
    GenreToJSON,
    GenreToJSONTyped,
} from './Genre';

/**
 * 
 * @export
 * @interface GenreIdentitiesOrValues
 */
export interface GenreIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof GenreIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<Genre>}
     * @memberof GenreIdentitiesOrValues
     */
    readonly values?: Array<Genre> | null;
}

/**
 * Check if a given object implements the GenreIdentitiesOrValues interface.
 */
export function instanceOfGenreIdentitiesOrValues(value: object): value is GenreIdentitiesOrValues {
    return true;
}

export function GenreIdentitiesOrValuesFromJSON(json: any): GenreIdentitiesOrValues {
    return GenreIdentitiesOrValuesFromJSONTyped(json, false);
}

export function GenreIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(GenreFromJSON)),
    };
}

export function GenreIdentitiesOrValuesToJSON(json: any): GenreIdentitiesOrValues {
    return GenreIdentitiesOrValuesToJSONTyped(json, false);
}

export function GenreIdentitiesOrValuesToJSONTyped(value?: Omit<GenreIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

