/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Genre
 */
export interface Genre {
    /**
     * 
     * @type {string}
     * @memberof Genre
     */
    checksum?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Genre
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Genre
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Genre
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Genre
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Genre
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Genre
     */
    url?: string | null;
}

/**
 * Check if a given object implements the Genre interface.
 */
export function instanceOfGenre(value: object): value is Genre {
    return true;
}

export function GenreFromJSON(json: any): Genre {
    return GenreFromJSONTyped(json, false);
}

export function GenreFromJSONTyped(json: any, ignoreDiscriminator: boolean): Genre {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GenreToJSON(json: any): Genre {
    return GenreToJSONTyped(json, false);
}

export function GenreToJSONTyped(value?: Genre | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'url': value['url'],
    };
}

