/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvolvedCompany } from './InvolvedCompany';
import {
    InvolvedCompanyFromJSON,
    InvolvedCompanyFromJSONTyped,
    InvolvedCompanyToJSON,
    InvolvedCompanyToJSONTyped,
} from './InvolvedCompany';

/**
 * 
 * @export
 * @interface InvolvedCompanyIdentitiesOrValues
 */
export interface InvolvedCompanyIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof InvolvedCompanyIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<InvolvedCompany>}
     * @memberof InvolvedCompanyIdentitiesOrValues
     */
    readonly values?: Array<InvolvedCompany> | null;
}

/**
 * Check if a given object implements the InvolvedCompanyIdentitiesOrValues interface.
 */
export function instanceOfInvolvedCompanyIdentitiesOrValues(value: object): value is InvolvedCompanyIdentitiesOrValues {
    return true;
}

export function InvolvedCompanyIdentitiesOrValuesFromJSON(json: any): InvolvedCompanyIdentitiesOrValues {
    return InvolvedCompanyIdentitiesOrValuesFromJSONTyped(json, false);
}

export function InvolvedCompanyIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvolvedCompanyIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(InvolvedCompanyFromJSON)),
    };
}

export function InvolvedCompanyIdentitiesOrValuesToJSON(json: any): InvolvedCompanyIdentitiesOrValues {
    return InvolvedCompanyIdentitiesOrValuesToJSONTyped(json, false);
}

export function InvolvedCompanyIdentitiesOrValuesToJSONTyped(value?: Omit<InvolvedCompanyIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

