/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IRConnectedPlayer
 */
export interface IRConnectedPlayer {
    /**
     * 
     * @type {string}
     * @memberof IRConnectedPlayer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IRConnectedPlayer
     */
    steamId?: string;
    /**
     * 
     * @type {string}
     * @memberof IRConnectedPlayer
     */
    connectedTime?: string;
}

/**
 * Check if a given object implements the IRConnectedPlayer interface.
 */
export function instanceOfIRConnectedPlayer(value: object): value is IRConnectedPlayer {
    return true;
}

export function IRConnectedPlayerFromJSON(json: any): IRConnectedPlayer {
    return IRConnectedPlayerFromJSONTyped(json, false);
}

export function IRConnectedPlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IRConnectedPlayer {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'steamId': json['steamId'] == null ? undefined : json['steamId'],
        'connectedTime': json['connectedTime'] == null ? undefined : json['connectedTime'],
    };
}

export function IRConnectedPlayerToJSON(json: any): IRConnectedPlayer {
    return IRConnectedPlayerToJSONTyped(json, false);
}

export function IRConnectedPlayerToJSONTyped(value?: IRConnectedPlayer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'steamId': value['steamId'],
        'connectedTime': value['connectedTime'],
    };
}

