/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageSupport } from './LanguageSupport';
import {
    LanguageSupportFromJSON,
    LanguageSupportFromJSONTyped,
    LanguageSupportToJSON,
    LanguageSupportToJSONTyped,
} from './LanguageSupport';

/**
 * 
 * @export
 * @interface LanguageSupportIdentitiesOrValues
 */
export interface LanguageSupportIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof LanguageSupportIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<LanguageSupport>}
     * @memberof LanguageSupportIdentitiesOrValues
     */
    readonly values?: Array<LanguageSupport> | null;
}

/**
 * Check if a given object implements the LanguageSupportIdentitiesOrValues interface.
 */
export function instanceOfLanguageSupportIdentitiesOrValues(value: object): value is LanguageSupportIdentitiesOrValues {
    return true;
}

export function LanguageSupportIdentitiesOrValuesFromJSON(json: any): LanguageSupportIdentitiesOrValues {
    return LanguageSupportIdentitiesOrValuesFromJSONTyped(json, false);
}

export function LanguageSupportIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageSupportIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(LanguageSupportFromJSON)),
    };
}

export function LanguageSupportIdentitiesOrValuesToJSON(json: any): LanguageSupportIdentitiesOrValues {
    return LanguageSupportIdentitiesOrValuesToJSONTyped(json, false);
}

export function LanguageSupportIdentitiesOrValuesToJSONTyped(value?: Omit<LanguageSupportIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

