/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';

/**
 * 
 * @export
 * @interface LanguageIdentityOrValue
 */
export interface LanguageIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof LanguageIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {Language}
     * @memberof LanguageIdentityOrValue
     */
    readonly value?: Language | null;
}

/**
 * Check if a given object implements the LanguageIdentityOrValue interface.
 */
export function instanceOfLanguageIdentityOrValue(value: object): value is LanguageIdentityOrValue {
    return true;
}

export function LanguageIdentityOrValueFromJSON(json: any): LanguageIdentityOrValue {
    return LanguageIdentityOrValueFromJSONTyped(json, false);
}

export function LanguageIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : LanguageFromJSON(json['value']),
    };
}

export function LanguageIdentityOrValueToJSON(json: any): LanguageIdentityOrValue {
    return LanguageIdentityOrValueToJSONTyped(json, false);
}

export function LanguageIdentityOrValueToJSONTyped(value?: Omit<LanguageIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

