/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageSupportType } from './LanguageSupportType';
import {
    LanguageSupportTypeFromJSON,
    LanguageSupportTypeFromJSONTyped,
    LanguageSupportTypeToJSON,
    LanguageSupportTypeToJSONTyped,
} from './LanguageSupportType';

/**
 * 
 * @export
 * @interface LanguageSupportTypeIdentityOrValue
 */
export interface LanguageSupportTypeIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof LanguageSupportTypeIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {LanguageSupportType}
     * @memberof LanguageSupportTypeIdentityOrValue
     */
    readonly value?: LanguageSupportType | null;
}

/**
 * Check if a given object implements the LanguageSupportTypeIdentityOrValue interface.
 */
export function instanceOfLanguageSupportTypeIdentityOrValue(value: object): value is LanguageSupportTypeIdentityOrValue {
    return true;
}

export function LanguageSupportTypeIdentityOrValueFromJSON(json: any): LanguageSupportTypeIdentityOrValue {
    return LanguageSupportTypeIdentityOrValueFromJSONTyped(json, false);
}

export function LanguageSupportTypeIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageSupportTypeIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : LanguageSupportTypeFromJSON(json['value']),
    };
}

export function LanguageSupportTypeIdentityOrValueToJSON(json: any): LanguageSupportTypeIdentityOrValue {
    return LanguageSupportTypeIdentityOrValueToJSONTyped(json, false);
}

export function LanguageSupportTypeIdentityOrValueToJSONTyped(value?: Omit<LanguageSupportTypeIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

