/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformIdentityOrValue } from './PlatformIdentityOrValue';
import {
    PlatformIdentityOrValueFromJSON,
    PlatformIdentityOrValueFromJSONTyped,
    PlatformIdentityOrValueToJSON,
    PlatformIdentityOrValueToJSONTyped,
} from './PlatformIdentityOrValue';
import type { GameIdentityOrValue } from './GameIdentityOrValue';
import {
    GameIdentityOrValueFromJSON,
    GameIdentityOrValueFromJSONTyped,
    GameIdentityOrValueToJSON,
    GameIdentityOrValueToJSONTyped,
} from './GameIdentityOrValue';

/**
 * 
 * @export
 * @interface MultiplayerMode
 */
export interface MultiplayerMode {
    /**
     * 
     * @type {boolean}
     * @memberof MultiplayerMode
     */
    campaignCoop?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof MultiplayerMode
     */
    checksum?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MultiplayerMode
     */
    dropIn?: boolean | null;
    /**
     * 
     * @type {GameIdentityOrValue}
     * @memberof MultiplayerMode
     */
    game?: GameIdentityOrValue | null;
    /**
     * 
     * @type {number}
     * @memberof MultiplayerMode
     */
    id?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof MultiplayerMode
     */
    lanCoop?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof MultiplayerMode
     */
    offlineCoop?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof MultiplayerMode
     */
    offlineCoopMax?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MultiplayerMode
     */
    offlineMax?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof MultiplayerMode
     */
    onlineCoop?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof MultiplayerMode
     */
    onlineCoopMax?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MultiplayerMode
     */
    onlineMax?: number | null;
    /**
     * 
     * @type {PlatformIdentityOrValue}
     * @memberof MultiplayerMode
     */
    platform?: PlatformIdentityOrValue | null;
    /**
     * 
     * @type {boolean}
     * @memberof MultiplayerMode
     */
    splitScreen?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof MultiplayerMode
     */
    splitScreenOnline?: boolean | null;
}

/**
 * Check if a given object implements the MultiplayerMode interface.
 */
export function instanceOfMultiplayerMode(value: object): value is MultiplayerMode {
    return true;
}

export function MultiplayerModeFromJSON(json: any): MultiplayerMode {
    return MultiplayerModeFromJSONTyped(json, false);
}

export function MultiplayerModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiplayerMode {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignCoop': json['campaignCoop'] == null ? undefined : json['campaignCoop'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'dropIn': json['dropIn'] == null ? undefined : json['dropIn'],
        'game': json['game'] == null ? undefined : GameIdentityOrValueFromJSON(json['game']),
        'id': json['id'] == null ? undefined : json['id'],
        'lanCoop': json['lanCoop'] == null ? undefined : json['lanCoop'],
        'offlineCoop': json['offlineCoop'] == null ? undefined : json['offlineCoop'],
        'offlineCoopMax': json['offlineCoopMax'] == null ? undefined : json['offlineCoopMax'],
        'offlineMax': json['offlineMax'] == null ? undefined : json['offlineMax'],
        'onlineCoop': json['onlineCoop'] == null ? undefined : json['onlineCoop'],
        'onlineCoopMax': json['onlineCoopMax'] == null ? undefined : json['onlineCoopMax'],
        'onlineMax': json['onlineMax'] == null ? undefined : json['onlineMax'],
        'platform': json['platform'] == null ? undefined : PlatformIdentityOrValueFromJSON(json['platform']),
        'splitScreen': json['splitScreen'] == null ? undefined : json['splitScreen'],
        'splitScreenOnline': json['splitScreenOnline'] == null ? undefined : json['splitScreenOnline'],
    };
}

export function MultiplayerModeToJSON(json: any): MultiplayerMode {
    return MultiplayerModeToJSONTyped(json, false);
}

export function MultiplayerModeToJSONTyped(value?: MultiplayerMode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaignCoop': value['campaignCoop'],
        'checksum': value['checksum'],
        'dropIn': value['dropIn'],
        'game': GameIdentityOrValueToJSON(value['game']),
        'id': value['id'],
        'lanCoop': value['lanCoop'],
        'offlineCoop': value['offlineCoop'],
        'offlineCoopMax': value['offlineCoopMax'],
        'offlineMax': value['offlineMax'],
        'onlineCoop': value['onlineCoop'],
        'onlineCoopMax': value['onlineCoopMax'],
        'onlineMax': value['onlineMax'],
        'platform': PlatformIdentityOrValueToJSON(value['platform']),
        'splitScreen': value['splitScreen'],
        'splitScreenOnline': value['splitScreenOnline'],
    };
}

