/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformType } from './PlatformType';
import {
    PlatformTypeFromJSON,
    PlatformTypeFromJSONTyped,
    PlatformTypeToJSON,
    PlatformTypeToJSONTyped,
} from './PlatformType';

/**
 * 
 * @export
 * @interface PlatformTypeIdentityOrValue
 */
export interface PlatformTypeIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof PlatformTypeIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {PlatformType}
     * @memberof PlatformTypeIdentityOrValue
     */
    readonly value?: PlatformType | null;
}

/**
 * Check if a given object implements the PlatformTypeIdentityOrValue interface.
 */
export function instanceOfPlatformTypeIdentityOrValue(value: object): value is PlatformTypeIdentityOrValue {
    return true;
}

export function PlatformTypeIdentityOrValueFromJSON(json: any): PlatformTypeIdentityOrValue {
    return PlatformTypeIdentityOrValueFromJSONTyped(json, false);
}

export function PlatformTypeIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformTypeIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : PlatformTypeFromJSON(json['value']),
    };
}

export function PlatformTypeIdentityOrValueToJSON(json: any): PlatformTypeIdentityOrValue {
    return PlatformTypeIdentityOrValueToJSONTyped(json, false);
}

export function PlatformTypeIdentityOrValueToJSONTyped(value?: Omit<PlatformTypeIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

