/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformVersion } from './PlatformVersion';
import {
    PlatformVersionFromJSON,
    PlatformVersionFromJSONTyped,
    PlatformVersionToJSON,
    PlatformVersionToJSONTyped,
} from './PlatformVersion';

/**
 * 
 * @export
 * @interface PlatformVersionIdentityOrValue
 */
export interface PlatformVersionIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof PlatformVersionIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {PlatformVersion}
     * @memberof PlatformVersionIdentityOrValue
     */
    readonly value?: PlatformVersion | null;
}

/**
 * Check if a given object implements the PlatformVersionIdentityOrValue interface.
 */
export function instanceOfPlatformVersionIdentityOrValue(value: object): value is PlatformVersionIdentityOrValue {
    return true;
}

export function PlatformVersionIdentityOrValueFromJSON(json: any): PlatformVersionIdentityOrValue {
    return PlatformVersionIdentityOrValueFromJSONTyped(json, false);
}

export function PlatformVersionIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformVersionIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : PlatformVersionFromJSON(json['value']),
    };
}

export function PlatformVersionIdentityOrValueToJSON(json: any): PlatformVersionIdentityOrValue {
    return PlatformVersionIdentityOrValueToJSONTyped(json, false);
}

export function PlatformVersionIdentityOrValueToJSONTyped(value?: Omit<PlatformVersionIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

