/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformWebsiteCategory } from './PlatformWebsiteCategory';
import {
    PlatformWebsiteCategoryFromJSON,
    PlatformWebsiteCategoryFromJSONTyped,
    PlatformWebsiteCategoryToJSON,
    PlatformWebsiteCategoryToJSONTyped,
} from './PlatformWebsiteCategory';

/**
 * 
 * @export
 * @interface PlatformWebsite
 */
export interface PlatformWebsite {
    /**
     * 
     * @type {PlatformWebsiteCategory}
     * @memberof PlatformWebsite
     */
    category?: PlatformWebsiteCategory | null;
    /**
     * 
     * @type {string}
     * @memberof PlatformWebsite
     */
    checksum?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlatformWebsite
     */
    id?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PlatformWebsite
     */
    trusted?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PlatformWebsite
     */
    url?: string | null;
}



/**
 * Check if a given object implements the PlatformWebsite interface.
 */
export function instanceOfPlatformWebsite(value: object): value is PlatformWebsite {
    return true;
}

export function PlatformWebsiteFromJSON(json: any): PlatformWebsite {
    return PlatformWebsiteFromJSONTyped(json, false);
}

export function PlatformWebsiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformWebsite {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : PlatformWebsiteCategoryFromJSON(json['category']),
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'id': json['id'] == null ? undefined : json['id'],
        'trusted': json['trusted'] == null ? undefined : json['trusted'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PlatformWebsiteToJSON(json: any): PlatformWebsite {
    return PlatformWebsiteToJSONTyped(json, false);
}

export function PlatformWebsiteToJSONTyped(value?: PlatformWebsite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': PlatformWebsiteCategoryToJSON(value['category']),
        'checksum': value['checksum'],
        'id': value['id'],
        'trusted': value['trusted'],
        'url': value['url'],
    };
}

