/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformWebsite } from './PlatformWebsite';
import {
    PlatformWebsiteFromJSON,
    PlatformWebsiteFromJSONTyped,
    PlatformWebsiteToJSON,
    PlatformWebsiteToJSONTyped,
} from './PlatformWebsite';

/**
 * 
 * @export
 * @interface PlatformWebsiteIdentitiesOrValues
 */
export interface PlatformWebsiteIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof PlatformWebsiteIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<PlatformWebsite>}
     * @memberof PlatformWebsiteIdentitiesOrValues
     */
    readonly values?: Array<PlatformWebsite> | null;
}

/**
 * Check if a given object implements the PlatformWebsiteIdentitiesOrValues interface.
 */
export function instanceOfPlatformWebsiteIdentitiesOrValues(value: object): value is PlatformWebsiteIdentitiesOrValues {
    return true;
}

export function PlatformWebsiteIdentitiesOrValuesFromJSON(json: any): PlatformWebsiteIdentitiesOrValues {
    return PlatformWebsiteIdentitiesOrValuesFromJSONTyped(json, false);
}

export function PlatformWebsiteIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformWebsiteIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(PlatformWebsiteFromJSON)),
    };
}

export function PlatformWebsiteIdentitiesOrValuesToJSON(json: any): PlatformWebsiteIdentitiesOrValues {
    return PlatformWebsiteIdentitiesOrValuesToJSONTyped(json, false);
}

export function PlatformWebsiteIdentitiesOrValuesToJSONTyped(value?: Omit<PlatformWebsiteIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

