/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Platform } from './Platform';
import {
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
    PlatformToJSONTyped,
} from './Platform';

/**
 * 
 * @export
 * @interface PlatformIdentitiesOrValues
 */
export interface PlatformIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof PlatformIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<Platform>}
     * @memberof PlatformIdentitiesOrValues
     */
    readonly values?: Array<Platform> | null;
}

/**
 * Check if a given object implements the PlatformIdentitiesOrValues interface.
 */
export function instanceOfPlatformIdentitiesOrValues(value: object): value is PlatformIdentitiesOrValues {
    return true;
}

export function PlatformIdentitiesOrValuesFromJSON(json: any): PlatformIdentitiesOrValues {
    return PlatformIdentitiesOrValuesFromJSONTyped(json, false);
}

export function PlatformIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(PlatformFromJSON)),
    };
}

export function PlatformIdentitiesOrValuesToJSON(json: any): PlatformIdentitiesOrValues {
    return PlatformIdentitiesOrValuesToJSONTyped(json, false);
}

export function PlatformIdentitiesOrValuesToJSONTyped(value?: Omit<PlatformIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

