/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlatformFamily
 */
export interface PlatformFamily {
    /**
     * 
     * @type {string}
     * @memberof PlatformFamily
     */
    checksum?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlatformFamily
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PlatformFamily
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlatformFamily
     */
    slug?: string | null;
}

/**
 * Check if a given object implements the PlatformFamily interface.
 */
export function instanceOfPlatformFamily(value: object): value is PlatformFamily {
    return true;
}

export function PlatformFamilyFromJSON(json: any): PlatformFamily {
    return PlatformFamilyFromJSONTyped(json, false);
}

export function PlatformFamilyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformFamily {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function PlatformFamilyToJSON(json: any): PlatformFamily {
    return PlatformFamilyToJSONTyped(json, false);
}

export function PlatformFamilyToJSONTyped(value?: PlatformFamily | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
    };
}

