/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlatformWebsiteCategory = {
    Official: 'Official',
    Wikia: 'Wikia',
    Wikipedia: 'Wikipedia',
    Facebook: 'Facebook',
    Twitter: 'Twitter',
    Twitch: 'Twitch',
    Instagram: 'Instagram',
    YouTube: 'YouTube',
    IPhone: 'iPhone',
    IPad: 'iPad',
    Android: 'Android',
    Steam: 'Steam',
    Reddit: 'Reddit',
    Discord: 'Discord',
    GooglePlus: 'GooglePlus',
    Tumblr: 'Tumblr',
    LinkedIn: 'LinkedIn',
    Pinterest: 'Pinterest',
    SoundCloud: 'SoundCloud'
} as const;
export type PlatformWebsiteCategory = typeof PlatformWebsiteCategory[keyof typeof PlatformWebsiteCategory];


export function instanceOfPlatformWebsiteCategory(value: any): boolean {
    for (const key in PlatformWebsiteCategory) {
        if (Object.prototype.hasOwnProperty.call(PlatformWebsiteCategory, key)) {
            if (PlatformWebsiteCategory[key as keyof typeof PlatformWebsiteCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PlatformWebsiteCategoryFromJSON(json: any): PlatformWebsiteCategory {
    return PlatformWebsiteCategoryFromJSONTyped(json, false);
}

export function PlatformWebsiteCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformWebsiteCategory {
    return json as PlatformWebsiteCategory;
}

export function PlatformWebsiteCategoryToJSON(value?: PlatformWebsiteCategory | null): any {
    return value as any;
}

export function PlatformWebsiteCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): PlatformWebsiteCategory {
    return value as PlatformWebsiteCategory;
}

