/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RConnectedPlayer
 */
export interface RConnectedPlayer {
    /**
     * 
     * @type {string}
     * @memberof RConnectedPlayer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RConnectedPlayer
     */
    steamId?: string;
    /**
     * 
     * @type {string}
     * @memberof RConnectedPlayer
     */
    connectedTime?: string;
}

/**
 * Check if a given object implements the RConnectedPlayer interface.
 */
export function instanceOfRConnectedPlayer(value: object): value is RConnectedPlayer {
    return true;
}

export function RConnectedPlayerFromJSON(json: any): RConnectedPlayer {
    return RConnectedPlayerFromJSONTyped(json, false);
}

export function RConnectedPlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RConnectedPlayer {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'steamId': json['steamId'] == null ? undefined : json['steamId'],
        'connectedTime': json['connectedTime'] == null ? undefined : json['connectedTime'],
    };
}

export function RConnectedPlayerToJSON(json: any): RConnectedPlayer {
    return RConnectedPlayerToJSONTyped(json, false);
}

export function RConnectedPlayerToJSONTyped(value?: RConnectedPlayer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'steamId': value['steamId'],
        'connectedTime': value['connectedTime'],
    };
}

