/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReactRequest
 */
export interface ReactRequest {
    /**
     * 
     * @type {string}
     * @memberof ReactRequest
     */
    roomId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReactRequest
     */
    messageId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReactRequest
     */
    emoji?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReactRequest
     */
    add?: boolean;
}

/**
 * Check if a given object implements the ReactRequest interface.
 */
export function instanceOfReactRequest(value: object): value is ReactRequest {
    return true;
}

export function ReactRequestFromJSON(json: any): ReactRequest {
    return ReactRequestFromJSONTyped(json, false);
}

export function ReactRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReactRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'roomId': json['roomId'] == null ? undefined : json['roomId'],
        'messageId': json['messageId'] == null ? undefined : json['messageId'],
        'emoji': json['emoji'] == null ? undefined : json['emoji'],
        'add': json['add'] == null ? undefined : json['add'],
    };
}

export function ReactRequestToJSON(json: any): ReactRequest {
    return ReactRequestToJSONTyped(json, false);
}

export function ReactRequestToJSONTyped(value?: ReactRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roomId': value['roomId'],
        'messageId': value['messageId'],
        'emoji': value['emoji'],
        'add': value['add'],
    };
}

