/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReleaseDate } from './ReleaseDate';
import {
    ReleaseDateFromJSON,
    ReleaseDateFromJSONTyped,
    ReleaseDateToJSON,
    ReleaseDateToJSONTyped,
} from './ReleaseDate';

/**
 * 
 * @export
 * @interface ReleaseDateIdentitiesOrValues
 */
export interface ReleaseDateIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof ReleaseDateIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<ReleaseDate>}
     * @memberof ReleaseDateIdentitiesOrValues
     */
    readonly values?: Array<ReleaseDate> | null;
}

/**
 * Check if a given object implements the ReleaseDateIdentitiesOrValues interface.
 */
export function instanceOfReleaseDateIdentitiesOrValues(value: object): value is ReleaseDateIdentitiesOrValues {
    return true;
}

export function ReleaseDateIdentitiesOrValuesFromJSON(json: any): ReleaseDateIdentitiesOrValues {
    return ReleaseDateIdentitiesOrValuesFromJSONTyped(json, false);
}

export function ReleaseDateIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseDateIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(ReleaseDateFromJSON)),
    };
}

export function ReleaseDateIdentitiesOrValuesToJSON(json: any): ReleaseDateIdentitiesOrValues {
    return ReleaseDateIdentitiesOrValuesToJSONTyped(json, false);
}

export function ReleaseDateIdentitiesOrValuesToJSONTyped(value?: Omit<ReleaseDateIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

