/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Screenshot } from './Screenshot';
import {
    ScreenshotFromJSON,
    ScreenshotFromJSONTyped,
    ScreenshotToJSON,
    ScreenshotToJSONTyped,
} from './Screenshot';

/**
 * 
 * @export
 * @interface ScreenshotIdentitiesOrValues
 */
export interface ScreenshotIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof ScreenshotIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<Screenshot>}
     * @memberof ScreenshotIdentitiesOrValues
     */
    readonly values?: Array<Screenshot> | null;
}

/**
 * Check if a given object implements the ScreenshotIdentitiesOrValues interface.
 */
export function instanceOfScreenshotIdentitiesOrValues(value: object): value is ScreenshotIdentitiesOrValues {
    return true;
}

export function ScreenshotIdentitiesOrValuesFromJSON(json: any): ScreenshotIdentitiesOrValues {
    return ScreenshotIdentitiesOrValuesFromJSONTyped(json, false);
}

export function ScreenshotIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenshotIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(ScreenshotFromJSON)),
    };
}

export function ScreenshotIdentitiesOrValuesToJSON(json: any): ScreenshotIdentitiesOrValues {
    return ScreenshotIdentitiesOrValuesToJSONTyped(json, false);
}

export function ScreenshotIdentitiesOrValuesToJSONTyped(value?: Omit<ScreenshotIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

