/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StartDateCategory = {
    Yyyymmmmdd: 'YYYYMMMMDD',
    Yyyymmmm: 'YYYYMMMM',
    Yyyy: 'YYYY',
    Yyyyq1: 'YYYYQ1',
    Yyyyq2: 'YYYYQ2',
    Yyyyq3: 'YYYYQ3',
    Yyyyq4: 'YYYYQ4',
    Tbd: 'TBD'
} as const;
export type StartDateCategory = typeof StartDateCategory[keyof typeof StartDateCategory];


export function instanceOfStartDateCategory(value: any): boolean {
    for (const key in StartDateCategory) {
        if (Object.prototype.hasOwnProperty.call(StartDateCategory, key)) {
            if (StartDateCategory[key as keyof typeof StartDateCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StartDateCategoryFromJSON(json: any): StartDateCategory {
    return StartDateCategoryFromJSONTyped(json, false);
}

export function StartDateCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartDateCategory {
    return json as StartDateCategory;
}

export function StartDateCategoryToJSON(value?: StartDateCategory | null): any {
    return value as any;
}

export function StartDateCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): StartDateCategory {
    return value as StartDateCategory;
}

