/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TR
 */
export interface TR {
    /**
     * 
     * @type {boolean}
     * @memberof TR
     */
    isSuccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TR
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TR
     */
    data?: string;
}

/**
 * Check if a given object implements the TR interface.
 */
export function instanceOfTR(value: object): value is TR {
    return true;
}

export function TRFromJSON(json: any): TR {
    return TRFromJSONTyped(json, false);
}

export function TRFromJSONTyped(json: any, ignoreDiscriminator: boolean): TR {
    if (json == null) {
        return json;
    }
    return {
        
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function TRToJSON(json: any): TR {
    return TRToJSONTyped(json, false);
}

export function TRToJSONTyped(value?: TR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isSuccess': value['isSuccess'],
        'message': value['message'],
        'data': value['data'],
    };
}

