/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserConnectionType = {
    LauncherOnly: 'LauncherOnly',
    AgentOnly: 'AgentOnly',
    Full: 'Full',
    Disconnected: 'Disconnected'
} as const;
export type UserConnectionType = typeof UserConnectionType[keyof typeof UserConnectionType];


export function instanceOfUserConnectionType(value: any): boolean {
    for (const key in UserConnectionType) {
        if (Object.prototype.hasOwnProperty.call(UserConnectionType, key)) {
            if (UserConnectionType[key as keyof typeof UserConnectionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserConnectionTypeFromJSON(json: any): UserConnectionType {
    return UserConnectionTypeFromJSONTyped(json, false);
}

export function UserConnectionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConnectionType {
    return json as UserConnectionType;
}

export function UserConnectionTypeToJSON(value?: UserConnectionType | null): any {
    return value as any;
}

export function UserConnectionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): UserConnectionType {
    return value as UserConnectionType;
}

