// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddGameData, AddGameResponses, CoverData, CoverResponses, DeleteGameData, DeleteGameResponses, DownloadImageData, DownloadImageResponses, GetAllConnectionsData, GetAllConnectionsResponses, GetALlUsernameConfigsData, GetALlUsernameConfigsResponses, GetAvailableGamesData, GetAvailableGamesResponses, GetAvatarData, GetAvatarResponses, GetFoldersData, GetFoldersResponses, GetGameSizeData, GetGameSizeResponses, GetGameTrailerData, GetGameTrailerResponses, GetLocalGamesDirData, GetLocalGamesDirResponses, GetOnlineUsersData, GetOnlineUsersResponses, GetUsernameConfigData, GetUsernameConfigResponses, GetUsernameFileConfigData, GetUsernameFileConfigResponses, ListGameStartExecutablesData, ListGameStartExecutablesResponses, LoginData, LoginResponses, LogoData, LogoResponses, RefreshGamesData, RefreshGamesResponses, SearchGameData, SearchGameResponses, SearchLogosData, SearchLogosResponses, SetLocalGamesDirData, SetLocalGamesDirResponses, UpdateFeaturedGamesData, UpdateFeaturedGamesResponses, UserInfoData, UserInfoResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const login = <ThrowOnError extends boolean = false>(options?: Options<LoginData, ThrowOnError>) => {
    return (options?.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const userInfo = <ThrowOnError extends boolean = false>(options?: Options<UserInfoData, ThrowOnError>) => {
    return (options?.client ?? client).get<UserInfoResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Auth/userinfo',
        ...options
    });
};

export const getAvatar = <ThrowOnError extends boolean = false>(options: Options<GetAvatarData, ThrowOnError>) => {
    return (options.client ?? client).get<GetAvatarResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetAvatar/{userId}',
        ...options
    });
};

export const downloadImage = <ThrowOnError extends boolean = false>(options?: Options<DownloadImageData, ThrowOnError>) => {
    return (options?.client ?? client).get<DownloadImageResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/DownloadImage',
        ...options
    });
};

/**
 * Update the list of featured games
 */
export const updateFeaturedGames = <ThrowOnError extends boolean = false>(options?: Options<UpdateFeaturedGamesData, ThrowOnError>) => {
    return (options?.client ?? client).post<UpdateFeaturedGamesResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/UpdateFeaturedGames',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const cover = <ThrowOnError extends boolean = false>(options: Options<CoverData, ThrowOnError>) => {
    return (options.client ?? client).get<CoverResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/{gameSlug}/Cover',
        ...options
    });
};

export const logo = <ThrowOnError extends boolean = false>(options: Options<LogoData, ThrowOnError>) => {
    return (options.client ?? client).get<LogoResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/{gameSlug}/Logo',
        ...options
    });
};

/**
 * Search for a game by its folder name
 */
export const searchGame = <ThrowOnError extends boolean = false>(options?: Options<SearchGameData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchGameResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/SearchGame',
        ...options
    });
};

export const searchLogos = <ThrowOnError extends boolean = false>(options?: Options<SearchLogosData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchLogosResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/SearchLogos',
        ...options
    });
};

/**
 * List all available games
 */
export const getAvailableGames = <ThrowOnError extends boolean = false>(options?: Options<GetAvailableGamesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAvailableGamesResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/AvailableGames',
        ...options
    });
};

/**
 * Refresh the list of games from the server
 */
export const refreshGames = <ThrowOnError extends boolean = false>(options?: Options<RefreshGamesData, ThrowOnError>) => {
    return (options?.client ?? client).get<RefreshGamesResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/RefreshGames',
        ...options
    });
};

export const deleteGame = <ThrowOnError extends boolean = false>(options?: Options<DeleteGameData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteGameResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/DeleteGame',
        ...options
    });
};

export const setLocalGamesDir = <ThrowOnError extends boolean = false>(options?: Options<SetLocalGamesDirData, ThrowOnError>) => {
    return (options?.client ?? client).post<SetLocalGamesDirResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/SetLocalGamesDir',
        ...options
    });
};

export const getLocalGamesDir = <ThrowOnError extends boolean = false>(options?: Options<GetLocalGamesDirData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetLocalGamesDirResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetLocalGamesDir',
        ...options
    });
};

/**
 * Get a list of username configuration use to place the username in the game
 */
export const getUsernameConfig = <ThrowOnError extends boolean = false>(options?: Options<GetUsernameConfigData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsernameConfigResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetUsernameConfig',
        ...options
    });
};

/**
 * Get a list of username configurations use to place the username in the game
 */
export const getALlUsernameConfigs = <ThrowOnError extends boolean = false>(options?: Options<GetALlUsernameConfigsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetALlUsernameConfigsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetAllUsernameConfigs',
        ...options
    });
};

/**
 * Add a game to the list of available games
 */
export const addGame = <ThrowOnError extends boolean = false>(options?: Options<AddGameData, ThrowOnError>) => {
    return (options?.client ?? client).post<AddGameResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/AddGame',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Gets the game trailer from Steam API
 */
export const getGameTrailer = <ThrowOnError extends boolean = false>(options?: Options<GetGameTrailerData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetGameTrailerResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetGameTrailer',
        ...options
    });
};

export const getFolders = <ThrowOnError extends boolean = false>(options?: Options<GetFoldersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFoldersResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetFolderSlugs',
        ...options
    });
};

export const getOnlineUsers = <ThrowOnError extends boolean = false>(options?: Options<GetOnlineUsersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetOnlineUsersResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetOnlineUsers',
        ...options
    });
};

export const getAllConnections = <ThrowOnError extends boolean = false>(options?: Options<GetAllConnectionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllConnectionsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetUserConnections',
        ...options
    });
};

export const getUsernameFileConfig = <ThrowOnError extends boolean = false>(options?: Options<GetUsernameFileConfigData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsernameFileConfigResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetUsernameFileConfig',
        ...options
    });
};

export const getGameSize = <ThrowOnError extends boolean = false>(options?: Options<GetGameSizeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetGameSizeResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/GetGameSize',
        ...options
    });
};

export const listGameStartExecutables = <ThrowOnError extends boolean = false>(options?: Options<ListGameStartExecutablesData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListGameStartExecutablesResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/Server/ListGameStartExecutables',
        ...options
    });
};
