
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.0.1
 * Query Engine version: f09f2815f091dbba658cdcd2264306d88bb5bda6
 */
Prisma.prismaVersion = {
  client: "7.0.1",
  engine: "f09f2815f091dbba658cdcd2264306d88bb5bda6"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  email: 'email',
  role: 'role',
  status: 'status',
  expiresAt: 'expiresAt',
  inviterId: 'inviterId'
};

exports.Prisma.JwksScalarFieldEnum = {
  id: 'id',
  publicKey: 'publicKey',
  privateKey: 'privateKey',
  createdAt: 'createdAt'
};

exports.Prisma.MemberScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  createdAt: 'createdAt',
  metadata: 'metadata'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId',
  impersonatedBy: 'impersonatedBy',
  activeOrganizationId: 'activeOrganizationId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  username: 'username',
  role: 'role',
  banned: 'banned',
  banReason: 'banReason',
  banExpires: 'banExpires',
  displayUsername: 'displayUsername',
  lastLogin: 'lastLogin'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SidelinkScalarFieldEnum = {
  id: 'id',
  name: 'name',
  url: 'url',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy',
  hidden: 'hidden'
};

exports.Prisma.Username_file_configScalarFieldEnum = {
  id: 'id',
  folder_slug: 'folder_slug',
  path: 'path',
  variable: 'variable',
  config_type: 'config_type'
};

exports.Prisma.User_settingsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  local_games_dir: 'local_games_dir'
};

exports.Prisma.Game_sessionScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  game_slug: 'game_slug',
  start_time: 'start_time',
  end_time: 'end_time',
  total_seconds: 'total_seconds'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  url: 'url',
  start_time: 'start_time',
  end_time: 'end_time',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  updated_by: 'updated_by',
  location: 'location',
  image_url: 'image_url'
};

exports.Prisma.Global_settingsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  updated_by: 'updated_by'
};

exports.Prisma.GameScalarFieldEnum = {
  id: 'id',
  size_gb: 'size_gb',
  title: 'title',
  folder_slug: 'folder_slug',
  version: 'version',
  genres: 'genres',
  platforms: 'platforms',
  game_modes: 'game_modes',
  is_featured: 'is_featured',
  date_updated: 'date_updated',
  date_added: 'date_added',
  editor_name: 'editor_name',
  main_process_name: 'main_process_name',
  cover: 'cover',
  logo: 'logo',
  screenshots: 'screenshots',
  description: 'description',
  start_command: 'start_command',
  max_players: 'max_players',
  use_notifications: 'use_notifications',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  updated_by: 'updated_by'
};

exports.Prisma.Game_serverScalarFieldEnum = {
  id: 'id',
  game_slug: 'game_slug',
  game_title: 'game_title',
  type: 'type',
  port: 'port',
  description: 'description',
  name: 'name',
  monitor: 'monitor',
  last_detection_at: 'last_detection_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  updated_by: 'updated_by'
};

exports.Prisma.RoleScalarFieldEnum = {
  name: 'name',
  nameplate_decoration_animated: 'nameplate_decoration_animated',
  nameplate_decoration_static: 'nameplate_decoration_static',
  avatar_decoration_animated: 'avatar_decoration_animated',
  avatar_decoration_static: 'avatar_decoration_static'
};

exports.Prisma.User_gameScalarFieldEnum = {
  user_id: 'user_id',
  game_slug: 'game_slug',
  installed_at: 'installed_at'
};

exports.Prisma.User_game_favoriteScalarFieldEnum = {
  user_id: 'user_id',
  game_slug: 'game_slug',
  addedAt: 'addedAt'
};

exports.Prisma.FaqScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  published: 'published',
  position: 'position',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  updated_by: 'updated_by'
};

exports.Prisma.GuildScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  icon: 'icon',
  ownerId: 'ownerId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Guild_memberScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  userId: 'userId',
  nickname: 'nickname',
  roles: 'roles',
  joinedAt: 'joinedAt'
};

exports.Prisma.ChannelScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  name: 'name',
  slug: 'slug',
  type: 'type',
  topic: 'topic',
  position: 'position',
  isPrivate: 'isPrivate',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Channel_memberScalarFieldEnum = {
  channelId: 'channelId',
  userId: 'userId',
  addedAt: 'addedAt'
};

exports.Prisma.RoomScalarFieldEnum = {
  id: 'id',
  type: 'type',
  name: 'name',
  ownerId: 'ownerId',
  guildId: 'guildId',
  channelId: 'channelId',
  lastMessageAt: 'lastMessageAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Room_participantScalarFieldEnum = {
  roomId: 'roomId',
  userId: 'userId',
  joinedAt: 'joinedAt',
  isMuted: 'isMuted',
  isPinned: 'isPinned'
};

exports.Prisma.Dm_pair_uniqueScalarFieldEnum = {
  id: 'id',
  userA: 'userA',
  userB: 'userB',
  roomId: 'roomId'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  authorId: 'authorId',
  type: 'type',
  content: 'content',
  attachments: 'attachments',
  createdAt: 'createdAt',
  editedAt: 'editedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.Message_readScalarFieldEnum = {
  messageId: 'messageId',
  userId: 'userId',
  readAt: 'readAt'
};

exports.Prisma.Message_reactionScalarFieldEnum = {
  messageId: 'messageId',
  userId: 'userId',
  emoji: 'emoji',
  createdAt: 'createdAt'
};

exports.Prisma.Room_viewScalarFieldEnum = {
  roomId: 'roomId',
  userId: 'userId',
  lastSeenAt: 'lastSeenAt'
};

exports.Prisma.EFMigrationsHistoryScalarFieldEnum = {
  MigrationId: 'MigrationId',
  ProductVersion: 'ProductVersion'
};

exports.Prisma.EditionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.Edition_roomScalarFieldEnum = {
  id: 'id',
  editionId: 'editionId',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TableScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  name: 'name',
  positionX: 'positionX',
  positionY: 'positionY',
  width: 'width',
  height: 'height',
  capacity: 'capacity',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Table_seatScalarFieldEnum = {
  id: 'id',
  tableId: 'tableId',
  seatIndex: 'seatIndex',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.accountOrderByRelevanceFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  scope: 'scope',
  password: 'password'
};

exports.Prisma.invitationOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  email: 'email',
  role: 'role',
  status: 'status',
  inviterId: 'inviterId'
};

exports.Prisma.jwksOrderByRelevanceFieldEnum = {
  id: 'id',
  publicKey: 'publicKey',
  privateKey: 'privateKey'
};

exports.Prisma.memberOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  role: 'role'
};

exports.Prisma.organizationOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  metadata: 'metadata'
};

exports.Prisma.sessionOrderByRelevanceFieldEnum = {
  id: 'id',
  token: 'token',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId',
  impersonatedBy: 'impersonatedBy',
  activeOrganizationId: 'activeOrganizationId'
};

exports.Prisma.userOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  image: 'image',
  username: 'username',
  role: 'role',
  banReason: 'banReason',
  displayUsername: 'displayUsername'
};

exports.Prisma.verificationOrderByRelevanceFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value'
};

exports.Prisma.sidelinkOrderByRelevanceFieldEnum = {
  name: 'name',
  url: 'url',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.username_file_configOrderByRelevanceFieldEnum = {
  folder_slug: 'folder_slug',
  path: 'path',
  variable: 'variable',
  config_type: 'config_type'
};

exports.Prisma.user_settingsOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  local_games_dir: 'local_games_dir'
};

exports.Prisma.game_sessionOrderByRelevanceFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  game_slug: 'game_slug'
};

exports.Prisma.eventOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  url: 'url',
  created_by: 'created_by',
  updated_by: 'updated_by',
  location: 'location',
  image_url: 'image_url'
};

exports.Prisma.global_settingsOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value',
  created_by: 'created_by',
  updated_by: 'updated_by'
};

exports.Prisma.gameOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  folder_slug: 'folder_slug',
  version: 'version',
  genres: 'genres',
  platforms: 'platforms',
  game_modes: 'game_modes',
  editor_name: 'editor_name',
  main_process_name: 'main_process_name',
  cover: 'cover',
  logo: 'logo',
  screenshots: 'screenshots',
  description: 'description',
  start_command: 'start_command',
  created_by: 'created_by',
  updated_by: 'updated_by'
};

exports.Prisma.game_serverOrderByRelevanceFieldEnum = {
  game_slug: 'game_slug',
  game_title: 'game_title',
  type: 'type',
  description: 'description',
  name: 'name',
  created_by: 'created_by',
  updated_by: 'updated_by'
};

exports.Prisma.roleOrderByRelevanceFieldEnum = {
  name: 'name',
  nameplate_decoration_animated: 'nameplate_decoration_animated',
  nameplate_decoration_static: 'nameplate_decoration_static',
  avatar_decoration_animated: 'avatar_decoration_animated',
  avatar_decoration_static: 'avatar_decoration_static'
};

exports.Prisma.user_gameOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  game_slug: 'game_slug'
};

exports.Prisma.user_game_favoriteOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  game_slug: 'game_slug'
};

exports.Prisma.faqOrderByRelevanceFieldEnum = {
  question: 'question',
  answer: 'answer',
  created_by: 'created_by',
  updated_by: 'updated_by'
};

exports.Prisma.guildOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  icon: 'icon',
  ownerId: 'ownerId'
};

exports.Prisma.guild_memberOrderByRelevanceFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  userId: 'userId',
  nickname: 'nickname',
  roles: 'roles'
};

exports.Prisma.channelOrderByRelevanceFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  name: 'name',
  slug: 'slug',
  topic: 'topic',
  parentId: 'parentId'
};

exports.Prisma.channel_memberOrderByRelevanceFieldEnum = {
  channelId: 'channelId',
  userId: 'userId'
};

exports.Prisma.roomOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  ownerId: 'ownerId',
  guildId: 'guildId',
  channelId: 'channelId'
};

exports.Prisma.room_participantOrderByRelevanceFieldEnum = {
  roomId: 'roomId',
  userId: 'userId'
};

exports.Prisma.dm_pair_uniqueOrderByRelevanceFieldEnum = {
  id: 'id',
  userA: 'userA',
  userB: 'userB',
  roomId: 'roomId'
};

exports.Prisma.messageOrderByRelevanceFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  authorId: 'authorId',
  content: 'content',
  attachments: 'attachments'
};

exports.Prisma.message_readOrderByRelevanceFieldEnum = {
  messageId: 'messageId',
  userId: 'userId'
};

exports.Prisma.message_reactionOrderByRelevanceFieldEnum = {
  messageId: 'messageId',
  userId: 'userId',
  emoji: 'emoji'
};

exports.Prisma.room_viewOrderByRelevanceFieldEnum = {
  roomId: 'roomId',
  userId: 'userId'
};

exports.Prisma.EFMigrationsHistoryOrderByRelevanceFieldEnum = {
  MigrationId: 'MigrationId',
  ProductVersion: 'ProductVersion'
};

exports.Prisma.editionOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.edition_roomOrderByRelevanceFieldEnum = {
  id: 'id',
  editionId: 'editionId',
  name: 'name'
};

exports.Prisma.tableOrderByRelevanceFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  name: 'name'
};

exports.Prisma.table_seatOrderByRelevanceFieldEnum = {
  id: 'id',
  tableId: 'tableId',
  userId: 'userId'
};
exports.channel_type = exports.$Enums.channel_type = {
  TEXT: 'TEXT',
  VOICE: 'VOICE',
  CATEGORY: 'CATEGORY'
};

exports.room_type = exports.$Enums.room_type = {
  DM: 'DM',
  GROUP: 'GROUP',
  GUILD_CHANNEL: 'GUILD_CHANNEL'
};

exports.message_type = exports.$Enums.message_type = {
  TEXT: 'TEXT',
  SYSTEM: 'SYSTEM',
  EVENT: 'EVENT'
};

exports.Prisma.ModelName = {
  account: 'account',
  invitation: 'invitation',
  jwks: 'jwks',
  member: 'member',
  organization: 'organization',
  session: 'session',
  user: 'user',
  verification: 'verification',
  sidelink: 'sidelink',
  username_file_config: 'username_file_config',
  user_settings: 'user_settings',
  game_session: 'game_session',
  event: 'event',
  global_settings: 'global_settings',
  game: 'game',
  game_server: 'game_server',
  role: 'role',
  user_game: 'user_game',
  user_game_favorite: 'user_game_favorite',
  faq: 'faq',
  guild: 'guild',
  guild_member: 'guild_member',
  channel: 'channel',
  channel_member: 'channel_member',
  room: 'room',
  room_participant: 'room_participant',
  dm_pair_unique: 'dm_pair_unique',
  message: 'message',
  message_read: 'message_read',
  message_reaction: 'message_reaction',
  room_view: 'room_view',
  EFMigrationsHistory: 'EFMigrationsHistory',
  edition: 'edition',
  edition_room: 'edition_room',
  table: 'table',
  table_seat: 'table_seat'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
