/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Agent.App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HardDriveInfo,
  PhysicalDevices,
} from '../models/index';
import {
    HardDriveInfoFromJSON,
    HardDriveInfoToJSON,
    PhysicalDevicesFromJSON,
    PhysicalDevicesToJSON,
} from '../models/index';

/**
 * 
 */
export class MachineApi extends runtime.BaseAPI {

    /**
     */
    async getHardDrivesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HardDriveInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Machine/GetHardDrives`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HardDriveInfoFromJSON));
    }

    /**
     */
    async getHardDrives(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HardDriveInfo>> {
        const response = await this.getHardDrivesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getPhysicalConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PhysicalDevices>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Machine/GetPhysicalConfig`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PhysicalDevicesFromJSON(jsonValue));
    }

    /**
     */
    async getPhysicalConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PhysicalDevices> {
        const response = await this.getPhysicalConfigRaw(initOverrides);
        return await response.value();
    }

}
