/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Agent.App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GPUInfos
 */
export interface GPUInfos {
    /**
     * 
     * @type {string}
     * @memberof GPUInfos
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof GPUInfos
     */
    vram?: number;
}

/**
 * Check if a given object implements the GPUInfos interface.
 */
export function instanceOfGPUInfos(value: object): value is GPUInfos {
    return true;
}

export function GPUInfosFromJSON(json: any): GPUInfos {
    return GPUInfosFromJSONTyped(json, false);
}

export function GPUInfosFromJSONTyped(json: any, ignoreDiscriminator: boolean): GPUInfos {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'vram': json['vram'] == null ? undefined : json['vram'],
    };
}

export function GPUInfosToJSON(json: any): GPUInfos {
    return GPUInfosToJSONTyped(json, false);
}

export function GPUInfosToJSONTyped(value?: GPUInfos | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'vram': value['vram'],
    };
}

