/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgeRatingOrganizationIdentityOrValue } from './AgeRatingOrganizationIdentityOrValue';
import {
    AgeRatingOrganizationIdentityOrValueFromJSON,
    AgeRatingOrganizationIdentityOrValueFromJSONTyped,
    AgeRatingOrganizationIdentityOrValueToJSON,
    AgeRatingOrganizationIdentityOrValueToJSONTyped,
} from './AgeRatingOrganizationIdentityOrValue';
import type { AgeRatingCategoryIdentityOrValue } from './AgeRatingCategoryIdentityOrValue';
import {
    AgeRatingCategoryIdentityOrValueFromJSON,
    AgeRatingCategoryIdentityOrValueFromJSONTyped,
    AgeRatingCategoryIdentityOrValueToJSON,
    AgeRatingCategoryIdentityOrValueToJSONTyped,
} from './AgeRatingCategoryIdentityOrValue';
import type { AgeRatingContentDescriptionV2IdentitiesOrValues } from './AgeRatingContentDescriptionV2IdentitiesOrValues';
import {
    AgeRatingContentDescriptionV2IdentitiesOrValuesFromJSON,
    AgeRatingContentDescriptionV2IdentitiesOrValuesFromJSONTyped,
    AgeRatingContentDescriptionV2IdentitiesOrValuesToJSON,
    AgeRatingContentDescriptionV2IdentitiesOrValuesToJSONTyped,
} from './AgeRatingContentDescriptionV2IdentitiesOrValues';

/**
 * 
 * @export
 * @interface AgeRating
 */
export interface AgeRating {
    /**
     * 
     * @type {string}
     * @memberof AgeRating
     */
    checksum?: string | null;
    /**
     * 
     * @type {AgeRatingOrganizationIdentityOrValue}
     * @memberof AgeRating
     */
    organization?: AgeRatingOrganizationIdentityOrValue | null;
    /**
     * 
     * @type {AgeRatingCategoryIdentityOrValue}
     * @memberof AgeRating
     */
    ratingCategory?: AgeRatingCategoryIdentityOrValue | null;
    /**
     * 
     * @type {AgeRatingContentDescriptionV2IdentitiesOrValues}
     * @memberof AgeRating
     */
    ratingContentDescriptions?: AgeRatingContentDescriptionV2IdentitiesOrValues | null;
    /**
     * 
     * @type {string}
     * @memberof AgeRating
     */
    ratingCoverUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgeRating
     */
    synopsis?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgeRating
     */
    id?: number | null;
}

/**
 * Check if a given object implements the AgeRating interface.
 */
export function instanceOfAgeRating(value: object): value is AgeRating {
    return true;
}

export function AgeRatingFromJSON(json: any): AgeRating {
    return AgeRatingFromJSONTyped(json, false);
}

export function AgeRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRating {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'organization': json['organization'] == null ? undefined : AgeRatingOrganizationIdentityOrValueFromJSON(json['organization']),
        'ratingCategory': json['ratingCategory'] == null ? undefined : AgeRatingCategoryIdentityOrValueFromJSON(json['ratingCategory']),
        'ratingContentDescriptions': json['ratingContentDescriptions'] == null ? undefined : AgeRatingContentDescriptionV2IdentitiesOrValuesFromJSON(json['ratingContentDescriptions']),
        'ratingCoverUrl': json['ratingCoverUrl'] == null ? undefined : json['ratingCoverUrl'],
        'synopsis': json['synopsis'] == null ? undefined : json['synopsis'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AgeRatingToJSON(json: any): AgeRating {
    return AgeRatingToJSONTyped(json, false);
}

export function AgeRatingToJSONTyped(value?: AgeRating | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'organization': AgeRatingOrganizationIdentityOrValueToJSON(value['organization']),
        'ratingCategory': AgeRatingCategoryIdentityOrValueToJSON(value['ratingCategory']),
        'ratingContentDescriptions': AgeRatingContentDescriptionV2IdentitiesOrValuesToJSON(value['ratingContentDescriptions']),
        'ratingCoverUrl': value['ratingCoverUrl'],
        'synopsis': value['synopsis'],
        'id': value['id'],
    };
}

