/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgeRatingOrganization } from './AgeRatingOrganization';
import {
    AgeRatingOrganizationFromJSON,
    AgeRatingOrganizationFromJSONTyped,
    AgeRatingOrganizationToJSON,
    AgeRatingOrganizationToJSONTyped,
} from './AgeRatingOrganization';

/**
 * 
 * @export
 * @interface AgeRatingOrganizationIdentityOrValue
 */
export interface AgeRatingOrganizationIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof AgeRatingOrganizationIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {AgeRatingOrganization}
     * @memberof AgeRatingOrganizationIdentityOrValue
     */
    readonly value?: AgeRatingOrganization | null;
}

/**
 * Check if a given object implements the AgeRatingOrganizationIdentityOrValue interface.
 */
export function instanceOfAgeRatingOrganizationIdentityOrValue(value: object): value is AgeRatingOrganizationIdentityOrValue {
    return true;
}

export function AgeRatingOrganizationIdentityOrValueFromJSON(json: any): AgeRatingOrganizationIdentityOrValue {
    return AgeRatingOrganizationIdentityOrValueFromJSONTyped(json, false);
}

export function AgeRatingOrganizationIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRatingOrganizationIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : AgeRatingOrganizationFromJSON(json['value']),
    };
}

export function AgeRatingOrganizationIdentityOrValueToJSON(json: any): AgeRatingOrganizationIdentityOrValue {
    return AgeRatingOrganizationIdentityOrValueToJSONTyped(json, false);
}

export function AgeRatingOrganizationIdentityOrValueToJSONTyped(value?: Omit<AgeRatingOrganizationIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

