/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AgeRatingCategory = {
    Esrb: 'ESRB',
    Pegi: 'PEGI',
    Cero: 'CERO',
    Usk: 'USK',
    Grac: 'GRAC',
    ClassInd: 'CLASS_IND',
    Acb: 'ACB'
} as const;
export type AgeRatingCategory = typeof AgeRatingCategory[keyof typeof AgeRatingCategory];


export function instanceOfAgeRatingCategory(value: any): boolean {
    for (const key in AgeRatingCategory) {
        if (Object.prototype.hasOwnProperty.call(AgeRatingCategory, key)) {
            if (AgeRatingCategory[key as keyof typeof AgeRatingCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AgeRatingCategoryFromJSON(json: any): AgeRatingCategory {
    return AgeRatingCategoryFromJSONTyped(json, false);
}

export function AgeRatingCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRatingCategory {
    return json as AgeRatingCategory;
}

export function AgeRatingCategoryToJSON(value?: AgeRatingCategory | null): any {
    return value as any;
}

export function AgeRatingCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): AgeRatingCategory {
    return value as AgeRatingCategory;
}

