/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Category = {
    MainGame: 'MainGame',
    DlcAddon: 'DlcAddon',
    Expansion: 'Expansion',
    Bundle: 'Bundle',
    StandaloneExpansion: 'StandaloneExpansion',
    Mod: 'Mod',
    Episode: 'Episode',
    Season: 'Season',
    Remake: 'Remake',
    Remaster: 'Remaster',
    ExpandedGame: 'ExpandedGame',
    Port: 'Port',
    Fork: 'Fork',
    Pack: 'Pack',
    Update: 'Update'
} as const;
export type Category = typeof Category[keyof typeof Category];


export function instanceOfCategory(value: any): boolean {
    for (const key in Category) {
        if (Object.prototype.hasOwnProperty.call(Category, key)) {
            if (Category[key as keyof typeof Category] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
    return json as Category;
}

export function CategoryToJSON(value?: Category | null): any {
    return value as any;
}

export function CategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): Category {
    return value as Category;
}

