/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionRelation } from './CollectionRelation';
import {
    CollectionRelationFromJSON,
    CollectionRelationFromJSONTyped,
    CollectionRelationToJSON,
    CollectionRelationToJSONTyped,
} from './CollectionRelation';

/**
 * 
 * @export
 * @interface CollectionRelationIdentitiesOrValues
 */
export interface CollectionRelationIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof CollectionRelationIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<CollectionRelation>}
     * @memberof CollectionRelationIdentitiesOrValues
     */
    readonly values?: Array<CollectionRelation> | null;
}

/**
 * Check if a given object implements the CollectionRelationIdentitiesOrValues interface.
 */
export function instanceOfCollectionRelationIdentitiesOrValues(value: object): value is CollectionRelationIdentitiesOrValues {
    return true;
}

export function CollectionRelationIdentitiesOrValuesFromJSON(json: any): CollectionRelationIdentitiesOrValues {
    return CollectionRelationIdentitiesOrValuesFromJSONTyped(json, false);
}

export function CollectionRelationIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionRelationIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(CollectionRelationFromJSON)),
    };
}

export function CollectionRelationIdentitiesOrValuesToJSON(json: any): CollectionRelationIdentitiesOrValues {
    return CollectionRelationIdentitiesOrValuesToJSONTyped(json, false);
}

export function CollectionRelationIdentitiesOrValuesToJSONTyped(value?: Omit<CollectionRelationIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

