/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CompanyWebsiteCategory = {
    Official: 'Official',
    Wikia: 'Wikia',
    Wikipedia: 'Wikipedia',
    Facebook: 'Facebook',
    Twitter: 'Twitter',
    Twitch: 'Twitch',
    Instagram: 'Instagram',
    YouTube: 'YouTube',
    IPhone: 'iPhone',
    IPad: 'iPad',
    Android: 'Android',
    Steam: 'Steam',
    Reddit: 'Reddit',
    Itch: 'Itch',
    EpicGames: 'EpicGames',
    Gog: 'GOG',
    Discord: 'Discord'
} as const;
export type CompanyWebsiteCategory = typeof CompanyWebsiteCategory[keyof typeof CompanyWebsiteCategory];


export function instanceOfCompanyWebsiteCategory(value: any): boolean {
    for (const key in CompanyWebsiteCategory) {
        if (Object.prototype.hasOwnProperty.call(CompanyWebsiteCategory, key)) {
            if (CompanyWebsiteCategory[key as keyof typeof CompanyWebsiteCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CompanyWebsiteCategoryFromJSON(json: any): CompanyWebsiteCategory {
    return CompanyWebsiteCategoryFromJSONTyped(json, false);
}

export function CompanyWebsiteCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyWebsiteCategory {
    return json as CompanyWebsiteCategory;
}

export function CompanyWebsiteCategoryToJSON(value?: CompanyWebsiteCategory | null): any {
    return value as any;
}

export function CompanyWebsiteCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): CompanyWebsiteCategory {
    return value as CompanyWebsiteCategory;
}

