/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyWebsite } from './CompanyWebsite';
import {
    CompanyWebsiteFromJSON,
    CompanyWebsiteFromJSONTyped,
    CompanyWebsiteToJSON,
    CompanyWebsiteToJSONTyped,
} from './CompanyWebsite';

/**
 * 
 * @export
 * @interface CompanyWebsiteIdentitiesOrValues
 */
export interface CompanyWebsiteIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof CompanyWebsiteIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<CompanyWebsite>}
     * @memberof CompanyWebsiteIdentitiesOrValues
     */
    readonly values?: Array<CompanyWebsite> | null;
}

/**
 * Check if a given object implements the CompanyWebsiteIdentitiesOrValues interface.
 */
export function instanceOfCompanyWebsiteIdentitiesOrValues(value: object): value is CompanyWebsiteIdentitiesOrValues {
    return true;
}

export function CompanyWebsiteIdentitiesOrValuesFromJSON(json: any): CompanyWebsiteIdentitiesOrValues {
    return CompanyWebsiteIdentitiesOrValuesFromJSONTyped(json, false);
}

export function CompanyWebsiteIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyWebsiteIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(CompanyWebsiteFromJSON)),
    };
}

export function CompanyWebsiteIdentitiesOrValuesToJSON(json: any): CompanyWebsiteIdentitiesOrValues {
    return CompanyWebsiteIdentitiesOrValuesToJSONTyped(json, false);
}

export function CompanyWebsiteIdentitiesOrValuesToJSONTyped(value?: Omit<CompanyWebsiteIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

