/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebsiteTypeIdentityOrValue } from './WebsiteTypeIdentityOrValue';
import {
    WebsiteTypeIdentityOrValueFromJSON,
    WebsiteTypeIdentityOrValueFromJSONTyped,
    WebsiteTypeIdentityOrValueToJSON,
    WebsiteTypeIdentityOrValueToJSONTyped,
} from './WebsiteTypeIdentityOrValue';

/**
 * 
 * @export
 * @interface CompanyWebsite
 */
export interface CompanyWebsite {
    /**
     * 
     * @type {string}
     * @memberof CompanyWebsite
     */
    checksum?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CompanyWebsite
     */
    id?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyWebsite
     */
    trusted?: boolean | null;
    /**
     * 
     * @type {WebsiteTypeIdentityOrValue}
     * @memberof CompanyWebsite
     */
    type?: WebsiteTypeIdentityOrValue | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyWebsite
     */
    url?: string | null;
}

/**
 * Check if a given object implements the CompanyWebsite interface.
 */
export function instanceOfCompanyWebsite(value: object): value is CompanyWebsite {
    return true;
}

export function CompanyWebsiteFromJSON(json: any): CompanyWebsite {
    return CompanyWebsiteFromJSONTyped(json, false);
}

export function CompanyWebsiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyWebsite {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'id': json['id'] == null ? undefined : json['id'],
        'trusted': json['trusted'] == null ? undefined : json['trusted'],
        'type': json['type'] == null ? undefined : WebsiteTypeIdentityOrValueFromJSON(json['type']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function CompanyWebsiteToJSON(json: any): CompanyWebsite {
    return CompanyWebsiteToJSONTyped(json, false);
}

export function CompanyWebsiteToJSONTyped(value?: CompanyWebsite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'id': value['id'],
        'trusted': value['trusted'],
        'type': WebsiteTypeIdentityOrValueToJSON(value['type']),
        'url': value['url'],
    };
}

