/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyStatus } from './CompanyStatus';
import {
    CompanyStatusFromJSON,
    CompanyStatusFromJSONTyped,
    CompanyStatusToJSON,
    CompanyStatusToJSONTyped,
} from './CompanyStatus';

/**
 * 
 * @export
 * @interface CompanyStatusIdentityOrValue
 */
export interface CompanyStatusIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof CompanyStatusIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {CompanyStatus}
     * @memberof CompanyStatusIdentityOrValue
     */
    readonly value?: CompanyStatus | null;
}

/**
 * Check if a given object implements the CompanyStatusIdentityOrValue interface.
 */
export function instanceOfCompanyStatusIdentityOrValue(value: object): value is CompanyStatusIdentityOrValue {
    return true;
}

export function CompanyStatusIdentityOrValueFromJSON(json: any): CompanyStatusIdentityOrValue {
    return CompanyStatusIdentityOrValueFromJSONTyped(json, false);
}

export function CompanyStatusIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyStatusIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : CompanyStatusFromJSON(json['value']),
    };
}

export function CompanyStatusIdentityOrValueToJSON(json: any): CompanyStatusIdentityOrValue {
    return CompanyStatusIdentityOrValueToJSONTyped(json, false);
}

export function CompanyStatusIdentityOrValueToJSONTyped(value?: Omit<CompanyStatusIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

