/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyLogo
 */
export interface CompanyLogo {
    /**
     * 
     * @type {boolean}
     * @memberof CompanyLogo
     */
    alphaChannel?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyLogo
     */
    animated?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyLogo
     */
    checksum?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CompanyLogo
     */
    height?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CompanyLogo
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyLogo
     */
    imageId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyLogo
     */
    url?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CompanyLogo
     */
    width?: number | null;
}

/**
 * Check if a given object implements the CompanyLogo interface.
 */
export function instanceOfCompanyLogo(value: object): value is CompanyLogo {
    return true;
}

export function CompanyLogoFromJSON(json: any): CompanyLogo {
    return CompanyLogoFromJSONTyped(json, false);
}

export function CompanyLogoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyLogo {
    if (json == null) {
        return json;
    }
    return {
        
        'alphaChannel': json['alphaChannel'] == null ? undefined : json['alphaChannel'],
        'animated': json['animated'] == null ? undefined : json['animated'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'height': json['height'] == null ? undefined : json['height'],
        'id': json['id'] == null ? undefined : json['id'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'url': json['url'] == null ? undefined : json['url'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function CompanyLogoToJSON(json: any): CompanyLogo {
    return CompanyLogoToJSONTyped(json, false);
}

export function CompanyLogoToJSONTyped(value?: CompanyLogo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alphaChannel': value['alphaChannel'],
        'animated': value['animated'],
        'checksum': value['checksum'],
        'height': value['height'],
        'id': value['id'],
        'imageId': value['imageId'],
        'url': value['url'],
        'width': value['width'],
    };
}

