/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Cover } from './Cover';
import {
    CoverFromJSON,
    CoverFromJSONTyped,
    CoverToJSON,
    CoverToJSONTyped,
} from './Cover';

/**
 * 
 * @export
 * @interface CoverIdentityOrValue
 */
export interface CoverIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof CoverIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {Cover}
     * @memberof CoverIdentityOrValue
     */
    readonly value?: Cover | null;
}

/**
 * Check if a given object implements the CoverIdentityOrValue interface.
 */
export function instanceOfCoverIdentityOrValue(value: object): value is CoverIdentityOrValue {
    return true;
}

export function CoverIdentityOrValueFromJSON(json: any): CoverIdentityOrValue {
    return CoverIdentityOrValueFromJSONTyped(json, false);
}

export function CoverIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : CoverFromJSON(json['value']),
    };
}

export function CoverIdentityOrValueToJSON(json: any): CoverIdentityOrValue {
    return CoverIdentityOrValueToJSONTyped(json, false);
}

export function CoverIdentityOrValueToJSONTyped(value?: Omit<CoverIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

