/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDmRequest
 */
export interface CreateDmRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDmRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the CreateDmRequest interface.
 */
export function instanceOfCreateDmRequest(value: object): value is CreateDmRequest {
    return true;
}

export function CreateDmRequestFromJSON(json: any): CreateDmRequest {
    return CreateDmRequestFromJSONTyped(json, false);
}

export function CreateDmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function CreateDmRequestToJSON(json: any): CreateDmRequest {
    return CreateDmRequestToJSONTyped(json, false);
}

export function CreateDmRequestToJSONTyped(value?: CreateDmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

