/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateFormat
 */
export interface DateFormat {
    /**
     * 
     * @type {string}
     * @memberof DateFormat
     */
    checksum?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof DateFormat
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DateFormat
     */
    format?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof DateFormat
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof DateFormat
     */
    id?: number | null;
}

/**
 * Check if a given object implements the DateFormat interface.
 */
export function instanceOfDateFormat(value: object): value is DateFormat {
    return true;
}

export function DateFormatFromJSON(json: any): DateFormat {
    return DateFormatFromJSONTyped(json, false);
}

export function DateFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'format': json['format'] == null ? undefined : json['format'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function DateFormatToJSON(json: any): DateFormat {
    return DateFormatToJSONTyped(json, false);
}

export function DateFormatToJSONTyped(value?: DateFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'format': value['format'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'id': value['id'],
    };
}

