/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Franchise } from './Franchise';
import {
    FranchiseFromJSON,
    FranchiseFromJSONTyped,
    FranchiseToJSON,
    FranchiseToJSONTyped,
} from './Franchise';

/**
 * 
 * @export
 * @interface FranchiseIdentitiesOrValues
 */
export interface FranchiseIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof FranchiseIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<Franchise>}
     * @memberof FranchiseIdentitiesOrValues
     */
    readonly values?: Array<Franchise> | null;
}

/**
 * Check if a given object implements the FranchiseIdentitiesOrValues interface.
 */
export function instanceOfFranchiseIdentitiesOrValues(value: object): value is FranchiseIdentitiesOrValues {
    return true;
}

export function FranchiseIdentitiesOrValuesFromJSON(json: any): FranchiseIdentitiesOrValues {
    return FranchiseIdentitiesOrValuesFromJSONTyped(json, false);
}

export function FranchiseIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FranchiseIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(FranchiseFromJSON)),
    };
}

export function FranchiseIdentitiesOrValuesToJSON(json: any): FranchiseIdentitiesOrValues {
    return FranchiseIdentitiesOrValuesToJSONTyped(json, false);
}

export function FranchiseIdentitiesOrValuesToJSONTyped(value?: Omit<FranchiseIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

