/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Franchise } from './Franchise';
import {
    FranchiseFromJSON,
    FranchiseFromJSONTyped,
    FranchiseToJSON,
    FranchiseToJSONTyped,
} from './Franchise';

/**
 * 
 * @export
 * @interface FranchiseIdentityOrValue
 */
export interface FranchiseIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof FranchiseIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {Franchise}
     * @memberof FranchiseIdentityOrValue
     */
    readonly value?: Franchise | null;
}

/**
 * Check if a given object implements the FranchiseIdentityOrValue interface.
 */
export function instanceOfFranchiseIdentityOrValue(value: object): value is FranchiseIdentityOrValue {
    return true;
}

export function FranchiseIdentityOrValueFromJSON(json: any): FranchiseIdentityOrValue {
    return FranchiseIdentityOrValueFromJSONTyped(json, false);
}

export function FranchiseIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FranchiseIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : FranchiseFromJSON(json['value']),
    };
}

export function FranchiseIdentityOrValueToJSON(json: any): FranchiseIdentityOrValue {
    return FranchiseIdentityOrValueToJSONTyped(json, false);
}

export function FranchiseIdentityOrValueToJSONTyped(value?: Omit<FranchiseIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

