/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameEngine } from './GameEngine';
import {
    GameEngineFromJSON,
    GameEngineFromJSONTyped,
    GameEngineToJSON,
    GameEngineToJSONTyped,
} from './GameEngine';

/**
 * 
 * @export
 * @interface GameEngineIdentitiesOrValues
 */
export interface GameEngineIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof GameEngineIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<GameEngine>}
     * @memberof GameEngineIdentitiesOrValues
     */
    readonly values?: Array<GameEngine> | null;
}

/**
 * Check if a given object implements the GameEngineIdentitiesOrValues interface.
 */
export function instanceOfGameEngineIdentitiesOrValues(value: object): value is GameEngineIdentitiesOrValues {
    return true;
}

export function GameEngineIdentitiesOrValuesFromJSON(json: any): GameEngineIdentitiesOrValues {
    return GameEngineIdentitiesOrValuesFromJSONTyped(json, false);
}

export function GameEngineIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameEngineIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(GameEngineFromJSON)),
    };
}

export function GameEngineIdentitiesOrValuesToJSON(json: any): GameEngineIdentitiesOrValues {
    return GameEngineIdentitiesOrValuesToJSONTyped(json, false);
}

export function GameEngineIdentitiesOrValuesToJSONTyped(value?: Omit<GameEngineIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

