/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameLocalization } from './GameLocalization';
import {
    GameLocalizationFromJSON,
    GameLocalizationFromJSONTyped,
    GameLocalizationToJSON,
    GameLocalizationToJSONTyped,
} from './GameLocalization';

/**
 * 
 * @export
 * @interface GameLocalizationIdentityOrValue
 */
export interface GameLocalizationIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof GameLocalizationIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {GameLocalization}
     * @memberof GameLocalizationIdentityOrValue
     */
    readonly value?: GameLocalization | null;
}

/**
 * Check if a given object implements the GameLocalizationIdentityOrValue interface.
 */
export function instanceOfGameLocalizationIdentityOrValue(value: object): value is GameLocalizationIdentityOrValue {
    return true;
}

export function GameLocalizationIdentityOrValueFromJSON(json: any): GameLocalizationIdentityOrValue {
    return GameLocalizationIdentityOrValueFromJSONTyped(json, false);
}

export function GameLocalizationIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameLocalizationIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : GameLocalizationFromJSON(json['value']),
    };
}

export function GameLocalizationIdentityOrValueToJSON(json: any): GameLocalizationIdentityOrValue {
    return GameLocalizationIdentityOrValueToJSONTyped(json, false);
}

export function GameLocalizationIdentityOrValueToJSONTyped(value?: Omit<GameLocalizationIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

