/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameIdentityOrValue } from './GameIdentityOrValue';
import {
    GameIdentityOrValueFromJSON,
    GameIdentityOrValueFromJSONTyped,
    GameIdentityOrValueToJSON,
    GameIdentityOrValueToJSONTyped,
} from './GameIdentityOrValue';

/**
 * 
 * @export
 * @interface GameVideo
 */
export interface GameVideo {
    /**
     * 
     * @type {string}
     * @memberof GameVideo
     */
    checksum?: string | null;
    /**
     * 
     * @type {GameIdentityOrValue}
     * @memberof GameVideo
     */
    game?: GameIdentityOrValue | null;
    /**
     * 
     * @type {number}
     * @memberof GameVideo
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GameVideo
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameVideo
     */
    videoId?: string | null;
}

/**
 * Check if a given object implements the GameVideo interface.
 */
export function instanceOfGameVideo(value: object): value is GameVideo {
    return true;
}

export function GameVideoFromJSON(json: any): GameVideo {
    return GameVideoFromJSONTyped(json, false);
}

export function GameVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'game': json['game'] == null ? undefined : GameIdentityOrValueFromJSON(json['game']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'videoId': json['videoId'] == null ? undefined : json['videoId'],
    };
}

export function GameVideoToJSON(json: any): GameVideo {
    return GameVideoToJSONTyped(json, false);
}

export function GameVideoToJSONTyped(value?: GameVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'game': GameIdentityOrValueToJSON(value['game']),
        'id': value['id'],
        'name': value['name'],
        'videoId': value['videoId'],
    };
}

