/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameType } from './GameType';
import {
    GameTypeFromJSON,
    GameTypeFromJSONTyped,
    GameTypeToJSON,
    GameTypeToJSONTyped,
} from './GameType';

/**
 * 
 * @export
 * @interface GameTypeIdentityOrValue
 */
export interface GameTypeIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof GameTypeIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {GameType}
     * @memberof GameTypeIdentityOrValue
     */
    readonly value?: GameType | null;
}

/**
 * Check if a given object implements the GameTypeIdentityOrValue interface.
 */
export function instanceOfGameTypeIdentityOrValue(value: object): value is GameTypeIdentityOrValue {
    return true;
}

export function GameTypeIdentityOrValueFromJSON(json: any): GameTypeIdentityOrValue {
    return GameTypeIdentityOrValueFromJSONTyped(json, false);
}

export function GameTypeIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameTypeIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : GameTypeFromJSON(json['value']),
    };
}

export function GameTypeIdentityOrValueToJSON(json: any): GameTypeIdentityOrValue {
    return GameTypeIdentityOrValueToJSONTyped(json, false);
}

export function GameTypeIdentityOrValueToJSONTyped(value?: Omit<GameTypeIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

