/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameReleaseFormat } from './GameReleaseFormat';
import {
    GameReleaseFormatFromJSON,
    GameReleaseFormatFromJSONTyped,
    GameReleaseFormatToJSON,
    GameReleaseFormatToJSONTyped,
} from './GameReleaseFormat';

/**
 * 
 * @export
 * @interface GameReleaseFormatIdentityOrValue
 */
export interface GameReleaseFormatIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof GameReleaseFormatIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {GameReleaseFormat}
     * @memberof GameReleaseFormatIdentityOrValue
     */
    readonly value?: GameReleaseFormat | null;
}

/**
 * Check if a given object implements the GameReleaseFormatIdentityOrValue interface.
 */
export function instanceOfGameReleaseFormatIdentityOrValue(value: object): value is GameReleaseFormatIdentityOrValue {
    return true;
}

export function GameReleaseFormatIdentityOrValueFromJSON(json: any): GameReleaseFormatIdentityOrValue {
    return GameReleaseFormatIdentityOrValueFromJSONTyped(json, false);
}

export function GameReleaseFormatIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameReleaseFormatIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : GameReleaseFormatFromJSON(json['value']),
    };
}

export function GameReleaseFormatIdentityOrValueToJSON(json: any): GameReleaseFormatIdentityOrValue {
    return GameReleaseFormatIdentityOrValueToJSONTyped(json, false);
}

export function GameReleaseFormatIdentityOrValueToJSONTyped(value?: Omit<GameReleaseFormatIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

