/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameMode } from './GameMode';
import {
    GameModeFromJSON,
    GameModeFromJSONTyped,
    GameModeToJSON,
    GameModeToJSONTyped,
} from './GameMode';

/**
 * 
 * @export
 * @interface GameModeIdentitiesOrValues
 */
export interface GameModeIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof GameModeIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<GameMode>}
     * @memberof GameModeIdentitiesOrValues
     */
    readonly values?: Array<GameMode> | null;
}

/**
 * Check if a given object implements the GameModeIdentitiesOrValues interface.
 */
export function instanceOfGameModeIdentitiesOrValues(value: object): value is GameModeIdentitiesOrValues {
    return true;
}

export function GameModeIdentitiesOrValuesFromJSON(json: any): GameModeIdentitiesOrValues {
    return GameModeIdentitiesOrValuesFromJSONTyped(json, false);
}

export function GameModeIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameModeIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(GameModeFromJSON)),
    };
}

export function GameModeIdentitiesOrValuesToJSON(json: any): GameModeIdentitiesOrValues {
    return GameModeIdentitiesOrValuesToJSONTyped(json, false);
}

export function GameModeIdentitiesOrValuesToJSONTyped(value?: Omit<GameModeIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

