/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Language
 */
export interface Language {
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    checksum?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Language
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Language
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    locale?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    nativeName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Language
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the Language interface.
 */
export function instanceOfLanguage(value: object): value is Language {
    return true;
}

export function LanguageFromJSON(json: any): Language {
    return LanguageFromJSONTyped(json, false);
}

export function LanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Language {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'name': json['name'] == null ? undefined : json['name'],
        'nativeName': json['nativeName'] == null ? undefined : json['nativeName'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function LanguageToJSON(json: any): Language {
    return LanguageToJSONTyped(json, false);
}

export function LanguageToJSONTyped(value?: Language | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'id': value['id'],
        'locale': value['locale'],
        'name': value['name'],
        'nativeName': value['nativeName'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

