/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiplayerMode } from './MultiplayerMode';
import {
    MultiplayerModeFromJSON,
    MultiplayerModeFromJSONTyped,
    MultiplayerModeToJSON,
    MultiplayerModeToJSONTyped,
} from './MultiplayerMode';

/**
 * 
 * @export
 * @interface MultiplayerModeIdentitiesOrValues
 */
export interface MultiplayerModeIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof MultiplayerModeIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<MultiplayerMode>}
     * @memberof MultiplayerModeIdentitiesOrValues
     */
    readonly values?: Array<MultiplayerMode> | null;
}

/**
 * Check if a given object implements the MultiplayerModeIdentitiesOrValues interface.
 */
export function instanceOfMultiplayerModeIdentitiesOrValues(value: object): value is MultiplayerModeIdentitiesOrValues {
    return true;
}

export function MultiplayerModeIdentitiesOrValuesFromJSON(json: any): MultiplayerModeIdentitiesOrValues {
    return MultiplayerModeIdentitiesOrValuesFromJSONTyped(json, false);
}

export function MultiplayerModeIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiplayerModeIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(MultiplayerModeFromJSON)),
    };
}

export function MultiplayerModeIdentitiesOrValuesToJSON(json: any): MultiplayerModeIdentitiesOrValues {
    return MultiplayerModeIdentitiesOrValuesToJSONTyped(json, false);
}

export function MultiplayerModeIdentitiesOrValuesToJSONTyped(value?: Omit<MultiplayerModeIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

