/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformVersionCompany } from './PlatformVersionCompany';
import {
    PlatformVersionCompanyFromJSON,
    PlatformVersionCompanyFromJSONTyped,
    PlatformVersionCompanyToJSON,
    PlatformVersionCompanyToJSONTyped,
} from './PlatformVersionCompany';

/**
 * 
 * @export
 * @interface PlatformVersionCompanyIdentitiesOrValues
 */
export interface PlatformVersionCompanyIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof PlatformVersionCompanyIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<PlatformVersionCompany>}
     * @memberof PlatformVersionCompanyIdentitiesOrValues
     */
    readonly values?: Array<PlatformVersionCompany> | null;
}

/**
 * Check if a given object implements the PlatformVersionCompanyIdentitiesOrValues interface.
 */
export function instanceOfPlatformVersionCompanyIdentitiesOrValues(value: object): value is PlatformVersionCompanyIdentitiesOrValues {
    return true;
}

export function PlatformVersionCompanyIdentitiesOrValuesFromJSON(json: any): PlatformVersionCompanyIdentitiesOrValues {
    return PlatformVersionCompanyIdentitiesOrValuesFromJSONTyped(json, false);
}

export function PlatformVersionCompanyIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformVersionCompanyIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(PlatformVersionCompanyFromJSON)),
    };
}

export function PlatformVersionCompanyIdentitiesOrValuesToJSON(json: any): PlatformVersionCompanyIdentitiesOrValues {
    return PlatformVersionCompanyIdentitiesOrValuesToJSONTyped(json, false);
}

export function PlatformVersionCompanyIdentitiesOrValuesToJSONTyped(value?: Omit<PlatformVersionCompanyIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

