/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Platform } from './Platform';
import {
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
    PlatformToJSONTyped,
} from './Platform';

/**
 * 
 * @export
 * @interface PlatformIdentityOrValue
 */
export interface PlatformIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof PlatformIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {Platform}
     * @memberof PlatformIdentityOrValue
     */
    readonly value?: Platform | null;
}

/**
 * Check if a given object implements the PlatformIdentityOrValue interface.
 */
export function instanceOfPlatformIdentityOrValue(value: object): value is PlatformIdentityOrValue {
    return true;
}

export function PlatformIdentityOrValueFromJSON(json: any): PlatformIdentityOrValue {
    return PlatformIdentityOrValueFromJSONTyped(json, false);
}

export function PlatformIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : PlatformFromJSON(json['value']),
    };
}

export function PlatformIdentityOrValueToJSON(json: any): PlatformIdentityOrValue {
    return PlatformIdentityOrValueToJSONTyped(json, false);
}

export function PlatformIdentityOrValueToJSONTyped(value?: Omit<PlatformIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

