/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerPerspective } from './PlayerPerspective';
import {
    PlayerPerspectiveFromJSON,
    PlayerPerspectiveFromJSONTyped,
    PlayerPerspectiveToJSON,
    PlayerPerspectiveToJSONTyped,
} from './PlayerPerspective';

/**
 * 
 * @export
 * @interface PlayerPerspectiveIdentitiesOrValues
 */
export interface PlayerPerspectiveIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof PlayerPerspectiveIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<PlayerPerspective>}
     * @memberof PlayerPerspectiveIdentitiesOrValues
     */
    readonly values?: Array<PlayerPerspective> | null;
}

/**
 * Check if a given object implements the PlayerPerspectiveIdentitiesOrValues interface.
 */
export function instanceOfPlayerPerspectiveIdentitiesOrValues(value: object): value is PlayerPerspectiveIdentitiesOrValues {
    return true;
}

export function PlayerPerspectiveIdentitiesOrValuesFromJSON(json: any): PlayerPerspectiveIdentitiesOrValues {
    return PlayerPerspectiveIdentitiesOrValuesFromJSONTyped(json, false);
}

export function PlayerPerspectiveIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerPerspectiveIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(PlayerPerspectiveFromJSON)),
    };
}

export function PlayerPerspectiveIdentitiesOrValuesToJSON(json: any): PlayerPerspectiveIdentitiesOrValues {
    return PlayerPerspectiveIdentitiesOrValuesToJSONTyped(json, false);
}

export function PlayerPerspectiveIdentitiesOrValuesToJSONTyped(value?: Omit<PlayerPerspectiveIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

