/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerPerspective
 */
export interface PlayerPerspective {
    /**
     * 
     * @type {string}
     * @memberof PlayerPerspective
     */
    checksum?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PlayerPerspective
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerPerspective
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PlayerPerspective
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlayerPerspective
     */
    slug?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PlayerPerspective
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PlayerPerspective
     */
    url?: string | null;
}

/**
 * Check if a given object implements the PlayerPerspective interface.
 */
export function instanceOfPlayerPerspective(value: object): value is PlayerPerspective {
    return true;
}

export function PlayerPerspectiveFromJSON(json: any): PlayerPerspective {
    return PlayerPerspectiveFromJSONTyped(json, false);
}

export function PlayerPerspectiveFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerPerspective {
    if (json == null) {
        return json;
    }
    return {
        
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PlayerPerspectiveToJSON(json: any): PlayerPerspective {
    return PlayerPerspectiveToJSONTyped(json, false);
}

export function PlayerPerspectiveToJSONTyped(value?: PlayerPerspective | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checksum': value['checksum'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'url': value['url'],
    };
}

