/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReleaseDateCategory = {
    Yyyymmmmdd: 'YYYYMMMMDD',
    Yyyymmmm: 'YYYYMMMM',
    Yyyy: 'YYYY',
    Yyyyq1: 'YYYYQ1',
    Yyyyq2: 'YYYYQ2',
    Yyyyq3: 'YYYYQ3',
    Yyyyq4: 'YYYYQ4',
    Tbd: 'TBD'
} as const;
export type ReleaseDateCategory = typeof ReleaseDateCategory[keyof typeof ReleaseDateCategory];


export function instanceOfReleaseDateCategory(value: any): boolean {
    for (const key in ReleaseDateCategory) {
        if (Object.prototype.hasOwnProperty.call(ReleaseDateCategory, key)) {
            if (ReleaseDateCategory[key as keyof typeof ReleaseDateCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReleaseDateCategoryFromJSON(json: any): ReleaseDateCategory {
    return ReleaseDateCategoryFromJSONTyped(json, false);
}

export function ReleaseDateCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseDateCategory {
    return json as ReleaseDateCategory;
}

export function ReleaseDateCategoryToJSON(value?: ReleaseDateCategory | null): any {
    return value as any;
}

export function ReleaseDateCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): ReleaseDateCategory {
    return value as ReleaseDateCategory;
}

