/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReleaseDateRegion } from './ReleaseDateRegion';
import {
    ReleaseDateRegionFromJSON,
    ReleaseDateRegionFromJSONTyped,
    ReleaseDateRegionToJSON,
    ReleaseDateRegionToJSONTyped,
} from './ReleaseDateRegion';
import type { ReleaseDateCategory } from './ReleaseDateCategory';
import {
    ReleaseDateCategoryFromJSON,
    ReleaseDateCategoryFromJSONTyped,
    ReleaseDateCategoryToJSON,
    ReleaseDateCategoryToJSONTyped,
} from './ReleaseDateCategory';
import type { PlatformIdentityOrValue } from './PlatformIdentityOrValue';
import {
    PlatformIdentityOrValueFromJSON,
    PlatformIdentityOrValueFromJSONTyped,
    PlatformIdentityOrValueToJSON,
    PlatformIdentityOrValueToJSONTyped,
} from './PlatformIdentityOrValue';
import type { GameIdentityOrValue } from './GameIdentityOrValue';
import {
    GameIdentityOrValueFromJSON,
    GameIdentityOrValueFromJSONTyped,
    GameIdentityOrValueToJSON,
    GameIdentityOrValueToJSONTyped,
} from './GameIdentityOrValue';
import type { ReleaseDateStatusIdentityOrValue } from './ReleaseDateStatusIdentityOrValue';
import {
    ReleaseDateStatusIdentityOrValueFromJSON,
    ReleaseDateStatusIdentityOrValueFromJSONTyped,
    ReleaseDateStatusIdentityOrValueToJSON,
    ReleaseDateStatusIdentityOrValueToJSONTyped,
} from './ReleaseDateStatusIdentityOrValue';

/**
 * 
 * @export
 * @interface ReleaseDate
 */
export interface ReleaseDate {
    /**
     * 
     * @type {ReleaseDateCategory}
     * @memberof ReleaseDate
     */
    category?: ReleaseDateCategory | null;
    /**
     * 
     * @type {string}
     * @memberof ReleaseDate
     */
    checksum?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ReleaseDate
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ReleaseDate
     */
    date?: Date | null;
    /**
     * 
     * @type {GameIdentityOrValue}
     * @memberof ReleaseDate
     */
    game?: GameIdentityOrValue | null;
    /**
     * 
     * @type {number}
     * @memberof ReleaseDate
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ReleaseDate
     */
    human?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ReleaseDate
     */
    month?: number | null;
    /**
     * 
     * @type {PlatformIdentityOrValue}
     * @memberof ReleaseDate
     */
    platform?: PlatformIdentityOrValue | null;
    /**
     * 
     * @type {ReleaseDateRegion}
     * @memberof ReleaseDate
     */
    region?: ReleaseDateRegion | null;
    /**
     * 
     * @type {ReleaseDateStatusIdentityOrValue}
     * @memberof ReleaseDate
     */
    status?: ReleaseDateStatusIdentityOrValue | null;
    /**
     * 
     * @type {Date}
     * @memberof ReleaseDate
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ReleaseDate
     */
    year?: number | null;
}



/**
 * Check if a given object implements the ReleaseDate interface.
 */
export function instanceOfReleaseDate(value: object): value is ReleaseDate {
    return true;
}

export function ReleaseDateFromJSON(json: any): ReleaseDate {
    return ReleaseDateFromJSONTyped(json, false);
}

export function ReleaseDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseDate {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : ReleaseDateCategoryFromJSON(json['category']),
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'game': json['game'] == null ? undefined : GameIdentityOrValueFromJSON(json['game']),
        'id': json['id'] == null ? undefined : json['id'],
        'human': json['human'] == null ? undefined : json['human'],
        'month': json['month'] == null ? undefined : json['month'],
        'platform': json['platform'] == null ? undefined : PlatformIdentityOrValueFromJSON(json['platform']),
        'region': json['region'] == null ? undefined : ReleaseDateRegionFromJSON(json['region']),
        'status': json['status'] == null ? undefined : ReleaseDateStatusIdentityOrValueFromJSON(json['status']),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'year': json['year'] == null ? undefined : json['year'],
    };
}

export function ReleaseDateToJSON(json: any): ReleaseDate {
    return ReleaseDateToJSONTyped(json, false);
}

export function ReleaseDateToJSONTyped(value?: ReleaseDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': ReleaseDateCategoryToJSON(value['category']),
        'checksum': value['checksum'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'date': value['date'] == null ? undefined : ((value['date'] as any).toISOString()),
        'game': GameIdentityOrValueToJSON(value['game']),
        'id': value['id'],
        'human': value['human'],
        'month': value['month'],
        'platform': PlatformIdentityOrValueToJSON(value['platform']),
        'region': ReleaseDateRegionToJSON(value['region']),
        'status': ReleaseDateStatusIdentityOrValueToJSON(value['status']),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'year': value['year'],
    };
}

