/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoomDto
 */
export interface RoomDto {
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    guildId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    channelId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RoomDto
     */
    lastMessageAt?: Date | null;
}

/**
 * Check if a given object implements the RoomDto interface.
 */
export function instanceOfRoomDto(value: object): value is RoomDto {
    return true;
}

export function RoomDtoFromJSON(json: any): RoomDto {
    return RoomDtoFromJSONTyped(json, false);
}

export function RoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'guildId': json['guildId'] == null ? undefined : json['guildId'],
        'channelId': json['channelId'] == null ? undefined : json['channelId'],
        'lastMessageAt': json['lastMessageAt'] == null ? undefined : (new Date(json['lastMessageAt'])),
    };
}

export function RoomDtoToJSON(json: any): RoomDto {
    return RoomDtoToJSONTyped(json, false);
}

export function RoomDtoToJSONTyped(value?: RoomDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'name': value['name'],
        'guildId': value['guildId'],
        'channelId': value['channelId'],
        'lastMessageAt': value['lastMessageAt'] == null ? undefined : ((value['lastMessageAt'] as any).toISOString()),
    };
}

