/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StringTR
 */
export interface StringTR {
    /**
     * 
     * @type {boolean}
     * @memberof StringTR
     */
    isSuccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StringTR
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof StringTR
     */
    data?: string | null;
}

/**
 * Check if a given object implements the StringTR interface.
 */
export function instanceOfStringTR(value: object): value is StringTR {
    return true;
}

export function StringTRFromJSON(json: any): StringTR {
    return StringTRFromJSONTyped(json, false);
}

export function StringTRFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringTR {
    if (json == null) {
        return json;
    }
    return {
        
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function StringTRToJSON(json: any): StringTR {
    return StringTRToJSONTyped(json, false);
}

export function StringTRToJSONTyped(value?: StringTR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isSuccess': value['isSuccess'],
        'message': value['message'],
        'data': value['data'],
    };
}

