/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Theme } from './Theme';
import {
    ThemeFromJSON,
    ThemeFromJSONTyped,
    ThemeToJSON,
    ThemeToJSONTyped,
} from './Theme';

/**
 * 
 * @export
 * @interface ThemeIdentitiesOrValues
 */
export interface ThemeIdentitiesOrValues {
    /**
     * 
     * @type {Array<number>}
     * @memberof ThemeIdentitiesOrValues
     */
    readonly ids?: Array<number> | null;
    /**
     * 
     * @type {Array<Theme>}
     * @memberof ThemeIdentitiesOrValues
     */
    readonly values?: Array<Theme> | null;
}

/**
 * Check if a given object implements the ThemeIdentitiesOrValues interface.
 */
export function instanceOfThemeIdentitiesOrValues(value: object): value is ThemeIdentitiesOrValues {
    return true;
}

export function ThemeIdentitiesOrValuesFromJSON(json: any): ThemeIdentitiesOrValues {
    return ThemeIdentitiesOrValuesFromJSONTyped(json, false);
}

export function ThemeIdentitiesOrValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeIdentitiesOrValues {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(ThemeFromJSON)),
    };
}

export function ThemeIdentitiesOrValuesToJSON(json: any): ThemeIdentitiesOrValues {
    return ThemeIdentitiesOrValuesToJSONTyped(json, false);
}

export function ThemeIdentitiesOrValuesToJSONTyped(value?: Omit<ThemeIdentitiesOrValues, 'ids'|'values'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

