/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsernameFileConfig
 */
export interface UsernameFileConfig {
    /**
     * 
     * @type {number}
     * @memberof UsernameFileConfig
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UsernameFileConfig
     */
    folderSlug?: string;
    /**
     * 
     * @type {string}
     * @memberof UsernameFileConfig
     */
    configType?: string;
    /**
     * 
     * @type {string}
     * @memberof UsernameFileConfig
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof UsernameFileConfig
     */
    variable?: string | null;
}

/**
 * Check if a given object implements the UsernameFileConfig interface.
 */
export function instanceOfUsernameFileConfig(value: object): value is UsernameFileConfig {
    return true;
}

export function UsernameFileConfigFromJSON(json: any): UsernameFileConfig {
    return UsernameFileConfigFromJSONTyped(json, false);
}

export function UsernameFileConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsernameFileConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'folderSlug': json['folderSlug'] == null ? undefined : json['folderSlug'],
        'configType': json['configType'] == null ? undefined : json['configType'],
        'path': json['path'] == null ? undefined : json['path'],
        'variable': json['variable'] == null ? undefined : json['variable'],
    };
}

export function UsernameFileConfigToJSON(json: any): UsernameFileConfig {
    return UsernameFileConfigToJSONTyped(json, false);
}

export function UsernameFileConfigToJSONTyped(value?: UsernameFileConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'folderSlug': value['folderSlug'],
        'configType': value['configType'],
        'path': value['path'],
        'variable': value['variable'],
    };
}

