/* tslint:disable */
/* eslint-disable */
/**
 * NCorp.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebsiteType } from './WebsiteType';
import {
    WebsiteTypeFromJSON,
    WebsiteTypeFromJSONTyped,
    WebsiteTypeToJSON,
    WebsiteTypeToJSONTyped,
} from './WebsiteType';

/**
 * 
 * @export
 * @interface WebsiteTypeIdentityOrValue
 */
export interface WebsiteTypeIdentityOrValue {
    /**
     * 
     * @type {number}
     * @memberof WebsiteTypeIdentityOrValue
     */
    readonly id?: number | null;
    /**
     * 
     * @type {WebsiteType}
     * @memberof WebsiteTypeIdentityOrValue
     */
    readonly value?: WebsiteType | null;
}

/**
 * Check if a given object implements the WebsiteTypeIdentityOrValue interface.
 */
export function instanceOfWebsiteTypeIdentityOrValue(value: object): value is WebsiteTypeIdentityOrValue {
    return true;
}

export function WebsiteTypeIdentityOrValueFromJSON(json: any): WebsiteTypeIdentityOrValue {
    return WebsiteTypeIdentityOrValueFromJSONTyped(json, false);
}

export function WebsiteTypeIdentityOrValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteTypeIdentityOrValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : WebsiteTypeFromJSON(json['value']),
    };
}

export function WebsiteTypeIdentityOrValueToJSON(json: any): WebsiteTypeIdentityOrValue {
    return WebsiteTypeIdentityOrValueToJSONTyped(json, false);
}

export function WebsiteTypeIdentityOrValueToJSONTyped(value?: Omit<WebsiteTypeIdentityOrValue, 'id'|'value'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

